### ISSUE TITLE
Animation doesn't play on Xamarin.Forms iOS

### ISSUE THREAD

**Issue by alexmanie** [martijn00/LottieXamarin#100]
Hi, 
I'm new with Lottie.
I followed a couple of step-by-step to get Lottie working on Xamarin.Forms.

After running some examples successfully I wanted to add Lottie to my existing project. I did all the steps required (install NuGet's, adding json files, adding namespace on XAML ..) but when I run the app the animation doesn't run. I'm seeing a freeze finger doing nothing.

I'm trying to add that animation from lottiefiles web, which I understood needs to work in my app:
https://www.lottiefiles.com/419-like

Any tips on how can I know the detailed issue and resolve it?

Thanks in advance

**Comment by alexmanie** [comment]
More information on that. I'm using Prism.Forms on Xamarin to get MVVM and other sugar features.

**Comment by RocketPop** [comment]
I've noticed that some lottie animations will not autoplay even if AutoPlay="True" is set in the xaml. The "warning sign" one for me will not autoplay, but "soda_loader" will. Not sure why. I have to give the control an x:Name and then call anim.Play() in code somewhere

**Comment by Jhanbury** [comment]
@alexmanie same scenario here using Prism and Android working fine but iOS view is not rendering

**Comment by naweed** [comment]
Have same issue with prism. Works fine in android but displays nothing in ios. Any idea or solution.

**Comment by MohdH** [comment]
I've the issue using prism. It works only in Android! Any tips?

**Comment by daspuru** [comment]
Same issue here, using Prism. Xamarin.Forms. When I set the IsVisible Binding to true, the animation appears in view but stopped.

**Comment by frode** [comment]
Have you guys verified that the json filename is correct? iOS is case-sensitive and Android is not. 

Example:

demo.json is both on Android and iOS.

<lottie:AnimationView Grid.Row="2" Animation="Demo.json" AutoPlay="true" Loop="true" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" />

Android plays fine. iOS fails.
Notice the capital D in Demo.json. filename on disk is demo.json

@naweed @Jhanbury @alexmanie @MohdH

**Comment by RocketPop** [comment]
Thanks - I'll check, but it will animate just fine if I manually call Play() on the control...

**Comment by frode** [comment]
@RocketPop You also added AnimationViewRenderer.Init(); to iOS project's AppDelegate.cs (inside FinishedLaunching method)?

**Comment by azharuddinsayed** [comment]
i have written AnimationViewRenderer.Init(); in both android and ios but still animation is not working .
Please help me .

**Comment by frode** [comment]
@azharuddinsayed did you try multiple json files from lottiefiles.com to verify its not a faulty one?

**Comment by azharuddinsayed** [comment]
yes i have tried multiple files .

**Comment by azharuddinsayed** [comment]
we have to set the property of the json to **AndroidJavaLibrary** for Driod and for ios **BundleResource** and after setting the property it is not deploying . https://xamgirl.com/lottie-animations-step-by-step-in-xamarin-forms/

**Comment by frode** [comment]
If it's not deploying at all, then something else is wrong with your project..

**Comment by azharuddinsayed** [comment]
if i set the property as **AndroidAsset** then it is deploying but animation is not working ,
Please help me .

**Comment by azharuddinsayed** [comment]
And even it is also not showing any error simply it is not deploying build is successful

**Comment by frode** [comment]
Are you on Windows or MacOS? What does the Visual Studio "output" window say?

**Comment by azharuddinsayed** [comment]
I am in Windows. it is showing as error **0** but it is saying in prompt that there is deployment error after clicking ok, in the output windows it is showing nothing .

**Comment by azharuddinsayed** [comment]
The file is already in lowercase **pagination.json** .This file i have downloaded from https://www.lottiefiles.com/  .

**Comment by Whiskerc** [comment]
I have the same problem - I have a Xamarin Forms project using Prism (IOS)

When I place an animationview on a page it shows the first frame of the animation but does not play.
I have copied accross the example file from the XamarinForms demo (including play, pause and slider) and the calling play does nothing, however using the slider I am able to see the animation updating

I have checked my AppDelegate file and I do call the Init method

I'm now stuck and can see no exceptions being thrown

**Comment by Whiskerc** [comment]
[BlankApp1.zip](https://github.com/martijn00/LottieXamarin/files/1607945/BlankApp1.zip)
Further to my earlier comment, attached is a sample project, demonstrating the issue with Xamarin Forms + Prism + Lottie (using .net standard 2.0)

**Comment by daspuru** [comment]
@Whiskerc  Have you tried setting Speed="1" in the XAML? That is a bug from the latest version of Lottie's Nuget. Good luck!

**Comment by starl1n** [comment]
Hi any news regarding Xamarin.iOS? I was able to implement it on Xamarin.Forms with Prism, android works well, but iOS appears but don't play.

**Comment by Whiskerc** [comment]
@daspuru that works a dream

@starl1n - my iOS project using prism (dryioc) works now I set the speed to 1 in the xaml

**Comment by starl1n** [comment]
Thanks @Whiskerc for the response, I'm using Prism Unity 6.3.0, Forms 2.5.0.121934

my XAML is like this:

`   <forms:AnimationView x:Name="AnimationView" 
            Speed="1" 
                Animation="empty_box.json"  AutoPlay="True"  
                Loop="True" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />`

I initialize the Xamarin.iOS before and after (See a few demos that initialize in different positions) the   `LoadApplication(new App(new IOSInitializer()));`

with 
`AnimationViewRenderer.Init();
`

but with both ways the animation appear but don't play at all.

**Comment by TianVan** [comment]
oh,fuck me i have same question,but Android

**Comment by Whiskerc** [comment]
@starl1n  - I managed to get it all working using prism and Unity 7.0.0 prerelease (my templates would not let me deploy the 6.3.0 version)

Have you tried with other animations just in case the one you are using is broken?

**Comment by TianVan** [comment]
@daspuru i love you,man! save my time save my life

**Comment by starl1n** [comment]
@Whiskerc I can't update to pre 
**Could not install package 'Prism.Unity 7.0.0.269-pre'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

T_T

**Comment by martijn00** [comment]
I've released 2.4.1 with a fix for the speed.

**Comment by saadali21** [comment]
Hi @martijn00 I'm using version 2.5.1 and still I not getting the animation on iOS. In android it works fine but not smoothly.
- I folowed all the steps in this link https://xamgirl.com/lottie-animations-step-by-step-in-xamarin-forms/
- I'm using VS2017 on windows with android emulator, and xamarin live player for iOS device.
- I tested many JSON animations.
Any Ideas?

**Comment by Bejasc** [comment]
I also have an animation that is not playing smoothly. It's quite jittery in its appearance. I am using it as a loading spinner, is it possible to run on another thread or some other method to make it appear smoothlu? @martijn00

**Comment by adarshdev** [comment]
In iOS add it into your project and make sure you have the build action in Bundle Resource

**Comment by Zure1** [comment]
Not sure if it's obvious, for me it wasn't. You have to declare a **WidthRequest** and **HeightRequest**. Horizontal- and VerticalOptions aren't enough. With a Width and Height assigned, the animation renders correctly on my site.

**Comment by MNADEEMCH** [comment]
Why this is close even not fixed on xamarin forms ios 
android working fine with lottie json animation file and ios not display animation.
