### ISSUE TITLE
LottieAnimationView not displayed because it is too large to fit into a software layer

### ISSUE THREAD

**Issue by gianlucaparadise** [martijn00/LottieXamarin#105]
When I run Example.Forms.Droid project on my Samsung S6 edge I get the following log:

```
[View] LottieAnimationView not displayed because it is too large to fit into a software layer (or drawing cache), needs 15367680 bytes, only 14745600 available
```

This happens when using `LottieLogo1.json`, but not when using `Belo Foggy.json`.

I don't have this problem when I run Example.Droid project using this `fragment_list.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingBottom="32dp"
        android:background="@color/colorPrimary">
        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            app:lottie_fileName="LottieLogo1.json"
            app:lottie_loop="true" />
    </FrameLayout>
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layoutManager="LinearLayoutManager" />
</LinearLayout>
```

How can I solve this problem?

Thanks

**Comment by simonegarau** [comment]
Did you solve this? I have the same problem...

**Comment by cuiti** [comment]
Got here by googling that warning, I'm getting it using the native Android version of Lottie. I'd appreciate if anyone has a clue of what's going on :)

**Comment by rguilluy** [comment]
Same problem here, in Xamarin Forms, but occurs only on android device (or simulator) : 
` 
<StackLayout x:Name="layoutEmptyList" Grid.Row="2" Grid.Column="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="Black" Padding="2">
      <StackLayout Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="White">
       <StackLayout  VerticalOptions="Center"  HeightRequest="120">
            <forms:AnimationView x:Name="emptyAnimation" Animation="empty_list.json" Loop="true" AutoPlay="true" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />
        </StackLayout>
        </StackLayout>
 </StackLayout>`

The animation does show up sometimes, but half the time it doesn't and I can see this warning in logs : 

> LottieAnimationView not displayed because it is too large to fit into a software layer (or drawing cache) ...

**Comment by Umar3x** [comment]
Got the same prob with XF . Had to put the animationView in a layout with both vertical and layout option to FillAndExpand, and put a width and height request to the lottie animation ...

**Comment by rguilluy** [comment]
Indeed, adding withRequest & HeightRequest to the AnimationView fix the the bug.
