### ISSUE TITLE
iOS animation view not showing sometimes

### ISSUE THREAD

**Issue by LeoJHarris** [martijn00/LottieXamarin#106]
Hi, i am having a hard time tying to get the animation view to display on iOS, android it works fine but on iOS it doesn't in some layouts although it as mentioned it works fine on android.

Below is android:

![android](https://user-images.githubusercontent.com/5468757/31159463-caeace78-a925-11e7-9555-288d9c51e569.jpg)

Below is iOS:

![ios](https://user-images.githubusercontent.com/5468757/31159391-29b045ba-a925-11e7-8b8c-afed488d25e6.jpg)

The red line is a stack layout with the animationview inside

Code is as follows below:

  ```
 <RelativeLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <Image
            Aspect="AspectFill"
            Source="{x:Static helpers:Settings.DefaultBackgroundImage}"
            RelativeLayout.WidthConstraint= "{ConstraintExpression Type=RelativeToParent, Property=Width}"
            RelativeLayout.HeightConstraint= "{ConstraintExpression Type=RelativeToParent, Property=Height}" />
        <AbsoluteLayout x:Name="AbsoluteLayout"
                        RelativeLayout.WidthConstraint= "{ConstraintExpression Type=RelativeToParent, Property=Width}"
                        RelativeLayout.HeightConstraint= "{ConstraintExpression Type=RelativeToParent, Property=Height}">
            <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Orientation="Vertical" AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
                         AbsoluteLayout.LayoutFlags="All">
                <forms:CommonHeader x:Name="CommonHeader" />
                <StackLayout BackgroundColor="Red" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                    <forms1:AnimationView 
                        x:Name="AnimationView" 
                        Animation="video_cam.json" 
                        AutoPlay="True" Loop="true"
                        VerticalOptions="FillAndExpand"
                        HorizontalOptions="FillAndExpand" />
                </StackLayout>
```
               
Same code but android works/shows the animation the other doesn't? No idea whats causing this for iOS i have called AnimationViewRenderer.Init(); in iOS project and the correct .json in the iOS project.

I am using latest Xamarin.forms 2.4.0.282

**Comment by pfaucon** [comment]
Have you tried with the no extra layouts?  

I'm not an expert by any means, but when I added the view on my app it was compressed like that, not because it wasn't playing, but it was losing a constraint fight somewhere.

**Comment by LeoJHarris** [comment]
Yup i had moved it out so it wasnt as nested in other views and i could see the animation view in ios so there was no problem. But there is a problem that it does get compressed when nested in more or certain views situations.

Unfortunately the code snippet above was just to prove the point, in my code where i have the animation i dont have the fortune that i can move the animation view out. This should or one would expect to work regardless of how nested.

**Comment by pfaucon** [comment]
but can you place it inside of a view that has an enforced size? Maybe you are having problems with the nested stack layouts (both of which are vertical it looks like) ? 

Maybe you can use an absolute/relative layout so that the parent view has a specified size even if the child (LottieView) doesn't know how big it should be?

**Comment by OpticNectar** [comment]
I'm having this same issue. On certain pages it just doesn't show up. It seems if you have it nested within more than 2-3 layouts it doesn't show up. I tried giving it an exact size too and it didn't work either. I can see a background color if I add one though which is weird.

**Comment by Umar3x** [comment]
Hello,

I'm having this behavior too only on iOS. For what I've seen it seems that it does not show in a particular flow. 

For example, I got a loading lottie file playing when calling a rest service, and sometimes the lottie file does not show on iOS after being already played (but the layout is never changing at all, so its not the cause). Seems that showing the lottie file multiple times after showing one is causing the lottie animation not to be shown/played.

**Comment by Umar3x** [comment]
Hello all,
No news about that ?

**Comment by LeoJHarris** [comment]
Not from me sorry.

**Comment by Umar3x** [comment]
You still have this behavior ? 

My usage is quite simple, w/o nested layout in a single Rg.Plugin.PopUpPage, or something complex, still the lottie animation shows only a few times. I also have this prob on simple content pages, so I don't think this is happening because of the previous written package : 

```
 public LoadingPage(string textLoading)
        {
            var activityIndicator = new AnimationView
            {
                Animation = "loader.json",
                Loop = true,
                AutoPlay = true,
                WidthRequest = 120,
                HeightRequest = 120
            };

            var mainLayout = new StackLayout
            {
                Orientation = StackOrientation.Vertical,
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HorizontalOptions = LayoutOptions.CenterAndExpand
            };

            var labelLoading = new MR.Gestures.Label
            {
                TextColor = Color.Orange,
                Text = textLoading,
                HorizontalTextAlignment = TextAlignment.Center,
                VerticalTextAlignment = TextAlignment.Center
            };

            mainLayout.Children.Add(activityIndicator);
            mainLayout.Children.Add(labelLoading);
            CloseWhenBackgroundIsClicked = false;

            Content = mainLayout;
        }
```

**Comment by Umar3x** [comment]
@LeoJHarris  

I found out that setting autoplay to false on iOS and calling Play() method in the OnAppearing method of the page does fix the prob

**Comment by LeoJHarris** [comment]
@Umar3x Haven't tested that yet, did you simplify the layout for the above working solution?
