### ISSUE TITLE
Animation working great on preview, but totally broken on mobile. Help!

### ISSUE THREAD

**Issue by salmondesign** [martijn00/LottieXamarin#107]
Hi 

I've created a pretty basic animation which is to be used as an onboarding screen for iOS and Android using Xamarin. It works fine when I throw the .json file into the lottie files preview - https://www.lottiefiles.com/share/5uJU9w

But when viewing it on mobile (at least the simulator) it is really broken. I've gone through the file and cleaned up every layer, but still it's the same problem. 

It looks like the attached!:
![screen shot 2017-10-04 at 13 56 28](https://user-images.githubusercontent.com/8035711/31179583-da30c960-a90b-11e7-808e-d9f3bcb9e5b5.png)

Attached is the .aep file. 

Can anyone offer any suggestions as to why this might be happening? I thought it might be the semi-transparent, blurred overlay that was causing problems, but even with that swapped for an image, or removed entirely, it's the same problem. 

[overdraft-onboarding.aep.zip](https://github.com/martijn00/LottieXamarin/files/1356009/overdraft-onboarding.aep.zip)

**Comment by martijn00** [comment]
This is up to the native implementation of Lottie and not a problem in the Xamarin library
