### ISSUE TITLE
Clickable AnimationView in Xamarin Forms

### ISSUE THREAD

**Issue by johankson** [martijn00/LottieXamarin#109]
Are there any plans to add a Command property to the AnimationView or make GestureRecognizers to work with the AnimationView?

```cs 
// This does not work
AnimationView.GestureRecognizers.Add(new TapGestureRecognizer()
{
    Command = new Command(() => {
         var i = 42;  
    })
});
```

I'm interested in implementing either the Command property and/or fix the GestureRecognizer bug (if it is a bug).

**Comment by martijn00** [comment]
I would accept a PR to implement the Command property.

**Comment by JamesItSolutionsLtd** [comment]
@johankson Hi did you manage to work on the GestureRecognizer and/or command. Can someone point me in the right direction

**Comment by umairali612** [comment]
I have added 4 different types of click events for android. Should I make this a branch in this repo or make my own? I plan to add same click events for iOS.

**Comment by RustamIrzaev** [comment]
@johankson Just update yourXF.Lottie package to a new version. It has both - `ClickedCommand` and `OnClick` event.
