### ISSUE TITLE
Xamarin.Forms - Documentation (Class level and tutorial)

### ISSUE THREAD

**Issue by matthewrdev** [martijn00/LottieXamarin#11]
The Xamarin Forms integration needs both class level documentation (properties and methods documented) and a tutorial built on how to integrate and use the AnimationView class.

**Comment by xamarindevelopervietnam** [comment]
Please documentation how to make animation, key frames... and please check Xamarin Forms demo is not running.

**Comment by modplug** [comment]
Demo should be fixed in #14
