### ISSUE TITLE
LottieAnimationView PauseAnimation crash sometimes

### ISSUE THREAD

**Issue by ornolisvt** [martijn00/LottieXamarin#111]
I´m using lottie to display a effect animation. I have an solution with MvvmCross + Xamarin. In this solutions a have three fragments in a tablayout with viewpager. First tab show a lottie animation but sometimes when quickly navigating between tabs lottie animation crash on method PauseAnimation. a A stack trace part is:

10-25 10:33:52.268 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt: Stacktrace:
10-25 10:33:52.268 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at <unknown> <0xffffffff>
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_void_method (intptr,intptr&,intptr,intptr) <0x00007>
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at Java.Interop.JniEnvironment/InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo) [0x00053] in <6cd960837cc24c26bab2a0a29b597627>:0
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr) [0x0000e] in <d278c06ad5684d6882c743a94a93ebc2>:0
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at Com.Airbnb.Lottie.LottieAnimationView.PauseAnimation () [0x00043] in <95dbb3274e5741e9af61c71fc11705cf>:0
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at PayPhone.Customer.Droid.Fragments.WaitingPaymentRequestFragment.HideWaves (bool) [0x00036] in <182e7308dd144d2aa1ad25f6f5de6e75>:0
10-25 10:33:52.269 14528-14528/payPhone_Android.PayPhone_Android E/mono-rt:   at PayPhone.Customer.Droid.Fragments.WaitingPaymentRequestFragment.<OnCreateView>b__7_0 (object,System.ComponentModel.PropertyChangedEventArgs) [0x0002d] in <182e7308dd144d2aa1ad25f6f5de6e75>:0

How can I solve this problem?

**Comment by modplug** [comment]
@ornolisvt Can you provide a small repro project of the problem?

**Comment by ornolisvt** [comment]
Sorry for the late response. In the latest versions this error has not occurred anymore
Thank you
