### ISSUE TITLE
Animation inside CarouselView

### ISSUE THREAD

**Issue by lucasrloliveira** [martijn00/LottieXamarin#113]
Hey, I´m having a problem trying to use Lottie json animation within a carousel view, I intent to change the animation´s reference when swiping my carousel, and I want to start the new animation at this very moment, but when I try to set AutoPlay to false and IsPlaying to true when swiping, my animations weren´t able to start, if I set AutoPlay to true, the animations will start independently from my swipe actions, this if I leave Loop to true, does anyone have any sugestions on how to start it at the changeIndexEvent of my carouselView? I´m using Xamarin forms Carousel View.

**Comment by modplug** [comment]
@lucasrloliveira Can you provide a small repro for this issue?
