### ISSUE TITLE
Updated to Xamarin.Forms 2.5.0.121934 & Prism.Forms 6.3.0 and animations does not play now.

### ISSUE THREAD

**Issue by daspuru** [martijn00/LottieXamarin#123]
Hi !

First of all, thanks for your great software, I use Lottie a lot in my Apps. However this time I upgraded my packages to the latest versions and all animations inside my app stopped playing, they appear static, before updating the animations were fine. I am using Prism and updated packages too. Problem occurs in Android and iOS. I am using Xamarin.Forms. Here is my current package versions:

Xamarin.Forms 2.5.0.121934
Com.Airbnb.Xamarin.Forms.Lottie 2.4.0 (in PCL and platform projects)
Com.Airbnb.iOS.Lottie 2.1.5.0
Com.Airbnb.Android.Lottie 2.2.5.0
Prism.Forms 6.3.0
Prism.Unity.Forms 6.3.0
Unity 4.0.1

I cleaned and uninstalled apps after upgrade without success. I am also running the Init code in platforms:

IOS:
AnimationViewRenderer.Init();

Android:
AnimationViewRenderer.Init();

I also tried to start the animations in Codebehind without success.

What can be the problem? 

Thanks a lot!!

**Comment by daspuru** [comment]
I added a repo with a clean solution made with Visual Studio for Mac, with the Prism/Unity template. Just updated packages, added Lottie, compile and test and in iOS and Android. Neither platforms play the animation. 

I hope this source code can help to solve the issue. Thanks: Here the link to the repo:

[https://github.com/daspuru/LottiePrismTest](https://github.com/daspuru/LottiePrismTest)

**Comment by fabionuno** [comment]
@daspuru  Can you check if your problem is related to #121 ?

**Comment by modplug** [comment]
I will try to make a fix for #121 this weekend. Adding Speed="1" won't do any harm, and you can remove it when the new version has been released
