### ISSUE TITLE
Supporting ContentMode in Forms

### ISSUE THREAD

**Issue by daspuru** [martijn00/LottieXamarin#125]
Hi !

I had to make a Custom Renderer to display the animation and use ContentMode = ScaleAspectFill, which seems to be very useful for displaying full screen animations. Is it possible to bind this property to use it in XAML? something like ContentMode="ScaleAspectFill" and wala, that would be awesome!

Thanks a lot! :)

**Comment by umairali612** [comment]
You can use Vertical options and horizontal and set those to Fill and expand as well.
