### ISSUE TITLE
Android animation not working on v2.4.0 of Xamarin.Forms.Lottie 

### ISSUE THREAD

**Issue by CarlosMobileAppDeveloper** [martijn00/LottieXamarin#127]
I have the latest Xamarin.Forms installed, and all other parts of the project up to date, but v2.4.0 of Xamarin.Forms.Lottie breaks Android animation. Previous versions are working fine. (currently using v2.3.4).

Tested on Android v7.0, with 8.0 as target platform.
Xamarin.forms v2.5.0.121934

Note: Have not tested iOS.

**Comment by asthanarht** [comment]
You mean Animation is not working. Try set property Speed="1"

**Comment by martijn00** [comment]
I've released 2.4.1 with a fix for this.
