### ISSUE TITLE
iOS applications with LottieXamarin using XCode 8.2.1 cannot be generated

### ISSUE THREAD

**Issue by abrasat** [martijn00/LottieXamarin#131]
To generate and test Xamarin.Forms iOS applications I am using the iPhoneSimulator with an "older" MacBook, on which can be installed only XCode 8.2.1.
When trying to generate a sample Lottie-based iOS application (with the LinkerBehavior set to "Link Framework SDKs only") the compiler/linker fails with the message:

error : Native linking error: framework not found FileProvider for architecture x86_64

**Comment by abrasat** [comment]
The linker problem above "dissapears" by downgrading Com.Airbnb.Xamarin.Forms.Lottie to version 2.3.4 and using Xamarin.Forms version 2.4.xxx.

The linker error occurs as soon as upgrading Com.Airbnb.Xamarin.Forms.Lottie to version 2.4.1 and subsequently Xamarin.Forms to version 2.5.xxx.

**Comment by fabionuno** [comment]
Apple introduced the [FileProvider](https://developer.apple.com/documentation/fileprovider#topics) framework in In iOS 11 / XCode 9.0.

Maybe this link helps you
https://stackoverflow.com/a/46483043
