### ISSUE TITLE
iOS animation does'nt load and doesnt load first time on andorid

### ISSUE THREAD

**Issue by IeuanWalker** [martijn00/LottieXamarin#132]
Xamarin.forms: v2.5.0.122203
Lottie xamarin: v2.4.1
Lottie Android: v2.3.1
Lottie iOS: v2.1.5
Rg.Plugin.Popup: v1.0.4

I am using Xamarin.Forms and I have the animation working on Android, and the only issues are that the animation only loads when I visit the page the second time. (I'm using Rg.Plugins.Popup [GitHub](https://github.com/rotorgames/Rg.Plugins.Popup))

And on iOS the animation doesn't load at all (_no errors or crashes_).

**Comment by jensf-sidious** [comment]
Same issue here. I am not using the Popup Plugin. The Animation works fine on Android, but on iOS it only starts
if I visit the DetailPage the second time. As I am using the AnimationView from a template in App.xaml I am unable to play the Animation from CodeBehind file.

**Comment by martijn00** [comment]
Make sure to call Init before playing any animation.
