### ISSUE TITLE
Change AnimationView color

### ISSUE THREAD

**Issue by ypenia** [martijn00/LottieXamarin#134]
Is it possible to change the AnimationView color like on the IOS example?

animationView2.setValue(UIColor.green, forKeypath: "BG-On.Group 1.Fill 1.Color", atFrame: 0)

**Comment by fabionuno** [comment]
@ypenia Yes, it's. 

Using Lottie 2.5.0:
```csharp
var lotKeypath = LOTKeypath.KeypathWithString("BG-On.Group 1.Fill 1.Color");
var lotColor = LOTColorValueCallback.WithCGColor(UIColor.Green.CGColor);
animationView2.SetValueDelegate(lotColor, lotKeypath);

```

**Comment by ypenia** [comment]
Thanks for your response, sorry i did not mention that i'm using forms.
It look like it's working on IOS, but i can't get it work on forms.
Can show an example in Xamarin Forms please?
