### ISSUE TITLE
Failed to resolve "Airbnb.Lottie.LOTAnimationView" reference from "Lottie.iOS"

### ISSUE THREAD

**Issue by khle** [martijn00/LottieXamarin#147]
To fix https://github.com/martijn00/LottieXamarin/issues/140, I have made sure I have the latest Xamarin.Forms 2.5.0.280555 in all projects (forms, android, ios), latest Lottie 2.5.0.1 in all 3, latest Visual Studio for Mac 7.4.

The problem is now I'm getting the error: 

/Users/.../MTOUCH: Error MT2002: Failed to resolve "Airbnb.Lottie.LOTAnimationView" reference from "Lottie.iOS, Version=1.0.6641.24589, Culture=neutral, PublicKeyToken=null" (MT2002)

BTW, I have deleted bin/, obj/, clean, rebuild, rebuild all, restarted VS for Mac multiple times too. Have not restarted the computer however.

**Comment by martijn00** [comment]
Try version 2.5.1
