### ISSUE TITLE
Xamarin Forms UWP runtime exception

### ISSUE THREAD

**Issue by MattRames** [martijn00/LottieXamarin#149]
Using Lottie.Forms 2.5.0.1 with the 2.5.0 LottieUWP pacakge I get a runtime exception. 

System.IO.FileLoadException: 'Could not load file or assembly 'Lottie.Forms, Version=1.0.6641.24880, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)' 

This is on a fresh Xamarin Forms project. The last lottie forms package I can sort of get working is 2.4.0 however, the animation doesn't play at this version.

**Comment by MattRames** [comment]
After downgrading the forms project to netStandard 1.4 and adjusting the UWP projects target version to be uap (16299) and the minimum version to be 15063 the 2.5.0.1 package works but the animation is very slow on UWP. 

![8daf20cb-3b43-4dc9-b715-f286d5dd8692](https://user-images.githubusercontent.com/9450530/37308517-4c86ef12-260c-11e8-995d-0313deea63a7.GIF)

**Comment by MattRames** [comment]
I did get the animation to work on UWP but I had to do a weird nuget package configuration and the animation is very slow.

![image](https://user-images.githubusercontent.com/9450530/37312206-17e6866c-2618-11e8-9732-05b92fb2d746.png)

![image](https://user-images.githubusercontent.com/9450530/37312209-1fdb074e-2618-11e8-9824-4863f32f2de7.png)

**Comment by azchohfi** [comment]
Try updating LottieUWP to 2.5.1, it should be way faster.

**Comment by MattRames** [comment]
Using 2.5.1 in the package configuration above results in a runtime exception Method not found: 'Void LottieUWP.LottieAnimationView.set_Speed(Single)'.

Attempting to use all latest packages still results in the following exception:
 _System.IO.FileLoadException: 'Could not load file or assembly 'Lottie.Forms, Version=1.0.6641.24880, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'_

Here is a link to my test project. https://drive.google.com/file/d/1V4o58vmMVCzqRVrECeASsp_3O3d2WGXY/view?usp=sharing

**Comment by azchohfi** [comment]
This is due to a change from Speed(float) to Speed(double). #150 should fix it.

**Comment by MattRames** [comment]
@azchohfi any idea when the next LottieUWP, and LottieXamarinForms package will be released?

**Comment by azchohfi** [comment]
Yesterday I released LottieUWP 2.5.2. I still need to submit the PR for Lottie X.F.

**Comment by MattRames** [comment]
I'm getting the file not found exception again on 2.5.2

System.IO.FileNotFoundException: 'Could not load file or assembly 'Lottie.Forms, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

**Comment by azchohfi** [comment]
@martijn00, any idea?

**Comment by martijn00** [comment]
I think i fixed this in https://github.com/martijn00/LottieXamarin/commit/587b0bdfbcb640f9db3ce9985fab73be24cd1233

Will get a release out soon, please let me know if it works.

**Comment by MattRames** [comment]
@martijn00 Looks like 2.5.2.1 works. Thank you.
