### ISSUE TITLE
Animation is not working as expected

### ISSUE THREAD

**Issue by githubdigo** [martijn00/LottieXamarin#151]
[Animation.zip](https://github.com/martijn00/LottieXamarin/files/1818782/Animation.zip)

Hi ,
PFB my json for animation, its a simple dot moving around and its not playing in the way it animated in Adobe.
{
  "assets": [],
  "layers": [
    {
      "ddd": 0,
      "ind": 4,
      "ty": 4,
      "nm": "Shape Layer 6",
      "ks": {
        "o": { "k": 100 },
        "r": { "k": 0 },
        "p": { "k": [ 960, 540, 0 ] },
        "a": { "k": [ 0, 0, 0 ] },
        "s": { "k": [ 100, 100, 100 ] }
      },
      "ao": 0,
      "shapes": [
        {
          "ty": "gr",
          "it": [
            {
              "ind": 0,
              "ty": "sh",
              "ks": {
                "k": {
                  "i": [
                    [ 0, 0 ],
                    [ 0, 142.213 ],
                    [ -142.213, 0 ],
                    [ 0, 0 ],
                    [ 0, -55.229 ],
                    [ 0, 0 ],
                    [ 55.229, 0 ]
                  ],
                  "o": [
                    [ -142.213, 0 ],
                    [ 0, -142.213 ],
                    [ 0, 0 ],
                    [ 55.229, 0 ],
                    [ 0, 0 ],
                    [ 0, 55.229 ],
                    [ 0, 0 ]
                  ],
                  "v": [
                    [ -207, 253.5 ],
                    [ -464.5, -4 ],
                    [ -207, -261.5 ],
                    [ 364.5, -261.5 ],
                    [ 464.5, -161.5 ],
                    [ 464.5, 153.5 ],
                    [ 364.5, 253.5 ]
                  ],
                  "c": true
                }
              },
              "nm": "Path 1",
              "mn": "ADBE Vector Shape - Group"
            },
            {
              "ty": "mm",
              "mm": 2,
              "nm": "Merge Paths 1",
              "mn": "ADBE Vector Filter - Merge"
            },
            {
              "ty": "tr",
              "p": {
                "k": [ -135, 8 ],
                "ix": 2
              },
              "a": {
                "k": [ 0, 0 ],
                "ix": 1
              },
              "s": {
                "k": [ 100, 100 ],
                "ix": 3
              },
              "r": {
                "k": 0,
                "ix": 6
              },
              "o": {
                "k": 100,
                "ix": 7
              },
              "sk": {
                "k": 0,
                "ix": 4
              },
              "sa": {
                "k": 0,
                "ix": 5
              },
              "nm": "Transform"
            }
          ],
          "nm": "Rectangle 1",
          "np": 2,
          "mn": "ADBE Vector Group"
        },
        {
          "ty": "tm",
          "s": {
            "k": [
              {
                "i": {
                  "x": [ 0.667 ],
                  "y": [ 1 ]
                },
                "o": {
                  "x": [ 0.167 ],
                  "y": [ 0.167 ]
                },
                "n": [ "0p667_1_0p167_0p167" ],
                "t": 26,
                "s": [ 50 ],
                "e": [ 45 ]
              },
              {
                "i": {
                  "x": [ 0.667 ],
                  "y": [ 1 ]
                },
                "o": {
                  "x": [ 0.333 ],
                  "y": [ 0 ]
                },
                "n": [ "0p667_1_0p333_0" ],
                "t": 30,
                "s": [ 45 ],
                "e": [ 50 ]
              },
              { "t": 38 }
            ],
            "ix": 1
          },
          "e": {
            "k": 50.01,
            "ix": 2
          },
          "o": {
            "k": [
              {
                "i": {
                  "x": [ 0.25 ],
                  "y": [ 1 ]
                },
                "o": {
                  "x": [ 0.894 ],
                  "y": [ 0 ]
                },
                "n": [ "0p25_1_0p894_0" ],
                "t": 10,
                "s": [ -26 ],
                "e": [ 223.3 ]
              },
              { "t": 40 }
            ],
            "x": "var $bm_rt;\n$bm_rt = sum(value, 180);",
            "ix": 3
          },
          "m": 1,
          "ix": 2,
          "nm": "Trim Paths 1",
          "mn": "ADBE Vector Filter - Trim"
        },
        {
          "ty": "st",
          "fillEnabled": true,
          "c": { "k": [ 1, 1, 1, 1 ] },
          "o": { "k": 100 },
          "w": {
            "k": [
              {
                "i": {
                  "x": [ 0.5 ],
                  "y": [ 1 ]
                },
                "o": {
                  "x": [ 0.167 ],
                  "y": [ 0.167 ]
                },
                "n": [ "0p5_1_0p167_0p167" ],
                "t": 10,
                "s": [ 0 ],
                "e": [ 50 ]
              },
              { "t": 13 }
            ]
          },
          "lc": 2,
          "lj": 1,
          "ml": 4,
          "nm": "Stroke 1",
          "mn": "ADBE Vector Graphic - Stroke"
        }
      ],
      "ip": 10,
      "op": 40,
      "st": -10,
      "bm": 0,
      "sr": 1
    }
  ],
  "v": "4.5.0",
  "ddd": 0,
  "ip": 0,
  "op": 75,
  "fr": 25,
  "w": 1920,
  "h": 1080
}

Uploaded the Correct animation played in adobe and animation played in Lottie 
[Animation.zip](https://github.com/martijn00/LottieXamarin/files/1818789/Animation.zip)

**Comment by fabionuno** [comment]
Lottie uses a completely different render engine for Lottie iOS, Lottie Android and Lottie Web. So you can find different issues among versions.

I have tested your animation in Lottie Web and it works as expected.
![dot_lottie-web](https://user-images.githubusercontent.com/5355384/37783827-2c45872e-2dd5-11e8-94f7-4f254d8b1217.gif)

Since your issue is related to the render engine you need to address this to [Lottie iOS](https://github.com/airbnb/lottie-ios/issues) or [Lottie Android](https://github.com/airbnb/lottie-android/issues) team.
