### ISSUE TITLE
Animation is working only in second time (Xamarin Forms - Android

### ISSUE THREAD

**Issue by gravitpt** [martijn00/LottieXamarin#156]
HI, the Lottie is only working when showing the page in a second time.

I am working with Xamarin Forms building Android (Both last version). 

**XAML**

` <StackLayout VerticalOptions="CenterAndExpand"  HorizontalOptions="CenterAndExpand" >
            <forms:AnimationView 
                x:Name="animationView" 
                Speed="1"
                Animation="PinJump.json"
                Loop="true"
                AutoPlay="true"
                />
</StackLayout>`

**BehindCode**

`        public BuscarPage()
        {
            InitializeComponent();

            Title = "Buscando...";

            animationView.Animation = "PinJump.json";
            animationView.Loop = true;
            animationView.AutoPlay = true;
            animationView.Speed = 1; 
            animationView.Play();
        }
`

**Comment by fabionuno** [comment]
Oi @gravitpt. Quando você diz que somente funciona na segunda vez, o que é exatamente funcionar?
A animação não é exibida na primeira vez?
A animação é exibida mas não faz o auto play?

Poderia detalhar melhor o comportamento esperado e o atual?

**Comment by alexmartinezm** [comment]
Have you added `AnimationViewRenderer.Init();` in Android's MainActivity? (after Forms.Init)
