### ISSUE TITLE
Latest upgrade (2.5.1) causes AppCenter to fail iOS Builds 

### ISSUE THREAD

**Issue by rob-derosa** [martijn00/LottieXamarin#157]
After updating to v2.5.1, I am seeing this build error in Visual Studio App Center build for Xamarin.iOS apps:
All builds prior to updating the nuget succeeded.

MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.BlockLiteral::SetupBlockUnsafe(System.Delegate,System.Delegate)', referenced from the method 'System.Void Airbnb.Lottie.LOTAnimationView::PlayFromFrame(Foundation.NSNumber,Foundation.NSNumber,Airbnb.Lottie.LOTAnimationCompletionBlock)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Users/vsts/agent/2.131.0/work/1/s/Hunt.Mobile.iOS/Hunt.Mobile.iOS.csproj]

**Comment by martijn00** [comment]
Update to a newer Xamarin.iOS version: https://github.com/martijn00/LottieXamarin/issues/140

**Comment by rob-derosa** [comment]
I updated to target iOS 11.0 and the same build error persists. Is there a minimum version of iOS I need to target for 2.5.1?

**Comment by rob-derosa** [comment]
Moving AppCenter build to target 9.2 of Xcode and Mono 5.4.1 didn't seem to resolve the issue either.

**Comment by rob-derosa** [comment]
Is this really a close issue?

**Comment by mrtnkrstn** [comment]
Having the same issue

**Comment by soreygarcia** [comment]
Same here.

**Comment by drailan** [comment]
Same issue for me. did the same as @fgiacomelli ,

**Comment by adilhraza** [comment]
Folks, i was having the same issue, just changed the AppCenter build to target 9.3 of Xcode and Mono version to 5.8.1 and it builds fine now.
