### ISSUE TITLE
Xamarin.Forms setup leads to Error MT2002: Failed to resolve "System.Void ObjCRuntime.BindingImplAttribute::.ctor(ObjCRuntime.BindingImplOptions)

### ISSUE THREAD

**Issue by EeKay** [martijn00/LottieXamarin#159]
I've added version 2.5.2.1 of Com.Airbnb.Xamarin.Forms.lottie via the nuget to my shared project.
And I also added this version to my iOS project version (accompanied by the iOS.Lottie package).

I'm using Xamarin.Forms 2.5.0.280555 in all projects.

I could compile before, then I noticed I was missing the init call in the iOS project. So I added the packages, added
  using Lottie.Forms.iOS.Renderers;
and
  AnimationViewRenderer.Init();

now it won't compile anymore, showing:

/PROJECTS/MyProject/Src/myProject/iOS/MTOUCH: Error MT2002: Failed to resolve "System.Void ObjCRuntime.BindingImplAttribute::.ctor(ObjCRuntime.BindingImplOptions)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002) (myProject.iOS)

NOTEWORTHY: 
- Building for the Simulator seems to work but as soon as I want to build for a device this pops up..
- this happens both for Release and Debug
- I tried using 2.5.2 of your packages but that led to the same compile error

Any hints or tips to find out what might be going on here?

**Comment by EeKay** [comment]
i've just tried version 2.5.1 of LottieXamarin and that compiles

**Comment by martijn00** [comment]
Try looking at the already closed issues that answer this.

**Comment by EeKay** [comment]
I checked them out but couldn't find a good match. Found https://github.com/martijn00/LottieXamarin/issues/157 to have a close resemblance but updating Xamarin.iOS wasn't applicable for my situation.

Can you pls elaborate on what issue should contain the answer?

**Comment by Lapinou42** [comment]
Yep, got the same error as well.
I have the latest version of VS and Xamarin for Mac (Stable channel) and latest version of LottieXamarin.

**Comment by Umar3x** [comment]
Same error here with latest XF release. Working fine on Android though.

**Comment by robbiestells** [comment]
I'm having this issue as well, just on iOS. Android works great

**Comment by sylvain-toptal** [comment]
@martijn00 There seems to be a packaging issue with the latest version.  This is the crash I talked to you about yesterday.  Using version 2.5.1 works fine and is the same iOS library version and bindings.  So my guess is this is due to the move to NetStandard.  This issue should be reopened.

**Comment by robbiestells** [comment]
@sylvain-toptal I still have that issue with 2.5.1 as well

**Comment by sylvain-toptal** [comment]
@robbiestells Really?  I don't.  Did you try a clean rebuild?

**Comment by robbiestells** [comment]
@sylvain-toptal on 2.5.1 I'm getting this error:
ailed to resolve "System.Void ObjCRuntime.BindingImplAttribute::.ctor(ObjCRuntime.BindingImplOptions)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral

**Comment by sylvain-toptal** [comment]
I don't know about that, 2.5.1 seems to work for others, including myself.

**Comment by sylvain-toptal** [comment]
I'm on Windows, latest VS (15.7 I believe) but my colleague has the same on Mac High Sierra.  All using Xcode 9.3
