### ISSUE TITLE
Splash animation not started in Android

### ISSUE THREAD

**Issue by 07JP27** [martijn00/LottieXamarin#163]
I implemented splash animation to iOS and Android project using lottie in accordance with [THIS SITE](https://www.project-respite.com/lottie-xamarin-forms/).
It working well.
But the splash animation not started in **ONLY ANDROID** after I installed following nuget package.
Just installed, not wrote anything my code.

* Xamarin.GooglePlayServices.Base V42.1021.1
* Xamarin.GooglePlayServices.Basement V42.1021.1
* Xamarin.GooglePlayServices.Maps V42.1021.1
* Xamarin.GooglePlayServices.Tasks V42.1021.1
* Xamarin.Build.Download V0.4.2

I tried debugging. It seems that the OnCreate method has completed but OnAnimationEnd event has not handled in following code.

```SplashActivity.cs
namespace lottietest.Droid
{
    [Activity(Theme = "@style/Theme.Splash", MainLauncher = true, NoHistory = true)]
    public class SplashActivity : Activity, Animator.IAnimatorListener
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            SetContentView(Resource.Layout.Activity_Splash);

            var animationView = FindViewById<LottieAnimationView>(Resource.Id.animation_view);
            animationView.AddAnimatorListener(this);
        }

        public void OnAnimationEnd(Animator animation)
        {
            StartActivity(new Intent(Application.Context, typeof(MainActivity)));
        }
    }
}
```

My enviroment
* Xamarin.Forms V2.4.0.280
* Com.Airbnb.Android.Lottie V2.2.5.0
* Com.Airbnb.Xamarin.Forms.Lottie V2.3.4
* Visual Studio Community 2017 for Mac V7.4

Any advices or infomation for me?
Thank you.

**Comment by viniciusou** [comment]
We have seen a similar issue trying to use Lottie in an Xamarin.Android app that has Xamarin.GooglePlayServices packages installed.  

In our case after adding Lottie nuget package to the Xamarin.Android project we have the following error: "java.exe" exited with code 1

Removing Xamarin.GooglePlayServices packages goes away and the animations work correctly.

Our enviroment:

Xamarin.Android V8.3.0.19
Com.Airbnb.Android.Lottie V2.5.4
Visual Studio Community 2017 V15.7.0
Xamarin.GooglePlayServices.Base V60.1142.1
Xamarin.GooglePlayServices.Basement V60.1142.1
Xamarin.GooglePlayServices.Tasks V60.1142.1
Xamarin.GooglePlayServices.Location V60.1142.1

@07JP27, do you have any update about your issue?

**Comment by 07JP27** [comment]
@viniciusou 
I have little update.
It worked correctly after Xamarin.Forms nuget version upgrade to 2.5.0.280555 from above environment.
 **BUT ONLY WHEN DEBUG mode.**

This issue still happen when run release mode or install archived app.

I don't know why happen different phenomenon in depending on run mode.

**Comment by 07JP27** [comment]
@candidodmv No update. It still happening.

**Comment by martijn00** [comment]
Please try again with 2.6.0 and let me know if it still happens.

**Comment by 07JP27** [comment]
@martijn00 It looks like fixed. thank you :)

**Comment by luismts** [comment]
In my case, the animation gets freezing with the activity. I want an infinity progress bar running even though if I call `StartActivity(mainIntent);`. 

When I call StartAcitivity method the screen is freezing and I need to wait around 2-3 seconds before the new activity start (MainActivity - Xamarin Forms). Are you facing this before?

**Comment by 07JP27** [comment]
@luismts 
No. In my case, the animation freeze before run ```StartActivity(mainIntent);```.
So, ```StartActivity(mainIntent);``` is not called forever.

But now , I resolved this issue after try it https://github.com/martijn00/LottieXamarin/issues/163#issuecomment-418805653 .

**Comment by lucadello91** [comment]
I've the same error as @luismts. 
When I call `StartActivity(mainIntent);` the animation on screen is freezing for 2-4 seconds before the new form appear.

What can i do? Someone can help me?
