### ISSUE TITLE
Animation is flashing on xamarin forms

### ISSUE THREAD

**Issue by Umar3x** [martijn00/LottieXamarin#171]
Hello,

I've bought a package of icons made with AE and exported with Bodymovin.
Thing is it works absolutely well on demo file (with js and web lottie) but when I try to display it on Android with xamarin forms the animations works well but there are random flashes on the animation.

Files are quite huge, with 200+ images (PNG sequence) attached with the .json file. 

What could cause this behavior ? 
I'm using XF3.0 and latest lottie forms release. 

See video attached : https://youtu.be/frnESO2iCkE

Thanks.

**Comment by vincentcastagna** [comment]
You close an issue w/o any answers or clues?

**Comment by martijn00** [comment]
Try to reproduce on lottie native and open an issue in their repo.
