### ISSUE TITLE
Android Bottom Tabs

### ISSUE THREAD

**Issue by afk013** [martijn00/LottieXamarin#173]
Xamarin form 3.1 added bottom tabs on android [ 3.1 Release Notes](https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.1/3.1.0/#Android_Bottom_Tabs). 

When using the bottom tabs placement even adding the lottie forms package causes a Java.Lang.NullPointerException

### Steps to reproduce :scroll:

1. Create a basic xamarin forms apps with a tabbed page. Update xamarin forms to 3.1.

2. Set the android tab placement to bottom. 

```csharp

using Xamarin.Forms;
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.AndroidSpecific;
using Xamarin.Forms.Xaml;

namespace LottieBottomNavigation
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MainTabbedPage : Xamarin.Forms.TabbedPage
    {
        public MainTabbedPage()
        {
            InitializeComponent();

            //Sets Main tab bar to bottom of screen on android
            On<Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
            On<Android>().SetBarItemColor(Color.FromHex("#999999"));
            On<Android>().SetBarSelectedItemColor(Color.FromHex("#EB5D3F"));
            BarBackgroundColor = Color.FromHex("#F9F9F9");
        }
    }
}

```

3. Run the app on android. The tabs should display at the bottom of the page.

4. Add the lottie forms package to all projects and rerun the app. Android will now throw a Java.Lang.NullPointerException.

[Example Repro](https://github.com/StyleTech-Hull/LottieFormsDroidBottomTabsBug)
[Full Stacktrace](https://gist.github.com/afk013/1a992e8bf0acdf98c76c6cac4c026bc7)

### Expected behavior :thinking:
Tabs on android should display at the bottom of the page and lottie animations should be able to be added to a child page of the tabbed page.

### Actual behavior :bug:
Adding lottie forms the android project throws a Java.Lang.NullPointerException at runtime.

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Please try again with Lottie 2.6.0 and let me know if it doesn't work.
