### ISSUE TITLE
Lottie.Forms.Droid namespace is missing from build 2.5.4

### ISSUE THREAD

**Issue by PatrickMcDougle** [martijn00/LottieXamarin#174]
### Steps to reproduce :scroll:

1.  Build any project with version 2.5.4 for Android Xamarin Forms.

### Expected behavior :thinking:
When upgrading the project from 2.5.2.1 to 2.5.4, the line of code "AnimationViewRenderer.Init();" should not become invalid.

### Actual behavior :bug:
the project becomes unbuildable.

### Configuration :wrench:

**Version:** 2.x
2.5.4 has the issue.
2.5.2.1 works fine.

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You can just add the new `using` with the new namespace.

**Comment by mpalmer78** [comment]
I had this problem too. The default Android version when creating a Xamarin.Forms project in Visual Studio 2017 is Android 7.1, which caused the compiler to be unable to find Lottie.Forms.Droid namespace. Changing the target to Android 8.1 fixed this issue.

**Comment by thaldi** [comment]
I had same problem too on 2.7.0 version. Changing the target to Android 8.1 not fixed this issue for me. 2.6.0 version fixed my problem.

**Comment by MaxenceMax** [comment]
@martijn00 I still have this problem, with last Lottie Version(2.7.1), last MonoAndroid Version(9.0). Lottie.Forms.Android cannot be found, and AnimationViewRenderer cannot be called.
