### ISSUE TITLE
Unable to restart animation in iOS

### ISSUE THREAD

**Issue by less0** [martijn00/LottieXamarin#175]
### Steps to reproduce :scroll:

1. `AnimationView` in a Xamarin.Forms project

2. In code behind, `AnimationView.Pause()` and later `AnimationView.PlayProgressSegment(0, 1)` is called

### Expected behavior :thinking:
The animation should restart from the beginning.

### Actual behavior :bug:
The animation starts from where it has been paused.

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ✓] :iphone: iOS
- [  ] :robot: Android
- [  ] :checkered_flag: WPF
- [  ] :earth_americas: UWP
- [  ] :apple: MacOS
- [  ] :tv: tvOS
- [✓ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@RustamIrzaev can you check this?

**Comment by fabionuno** [comment]
@less0 This is the behavior defined by the native library. 
[If the current frame is greater than the start value passed to `PlayProgressSegment`, animation resume from current position.](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/Private/LOTAnimationView.m#L371)

To restart animation everytime, use `AnimationView.Stop()`
