### ISSUE TITLE
'app' is an undeclared prefix. In AXML

### ISSUE THREAD

**Issue by clovyclov** [martijn00/LottieXamarin#177]
### Steps to reproduce :scroll:

1. Copy the axml from the Xamarin Android readme 

```
<com.airbnb.lottie.LottieAnimationView
	android:id="@+id/animation_view"
	android:layout_width="wrap_content"
	android:layout_height="wrap_content"
	app:lottie_fileName="hello-world.json"
	app:lottie_loop="true"
	app:lottie_autoPlay="true" />
```

### Expected behavior :thinking:
Tell us what should happen

It should play the animation I'm assuming.

### Actual behavior :bug:
Tell us what happens instead

Instead, it says " 'app' is an undeclared prefix. Line 36, position 5. "

### Configuration :wrench:

**Version:** 2.x

**Platform:** 
- [x] :robot: Xamarin.Android

**Comment by clovyclov** [comment]
![screen shot 2018-07-17 at 5 01 17 pm](https://user-images.githubusercontent.com/4207477/42845165-14161fbe-89e3-11e8-9e04-9c6947457594.png)

**Comment by clovyclov** [comment]
And this happens when I remove the lines with the 'app' prefix in the xml

![screen shot 2018-07-17 at 5 02 15 pm](https://user-images.githubusercontent.com/4207477/42845200-3020605c-89e3-11e8-91f3-eeebecc7102d.png)

**Comment by MattWhiteProximity** [comment]
I'm getting exact same problem.

**Comment by clovyclov** [comment]
@MattWhiteProximity I figured it out. So "app" throws that issue because it's an undeclared xml namespace. For example, look at your outermost element. See how it shows 

`xmlns:android="http://schemas.android.com/apk/res/android"`

that means you are declaring "android" as a new xml namespace (xmlns). So the same must be done for "app". So just put this on the outermost layer and you should be set

`xmlns:app="http://schemas.android.com/apk/res-auto"`

Be sure to clean the solution, delete the bin and obj folders, and rebuild.

**Comment by MattWhiteProximity** [comment]
That makes complete sense! and works! thanks.

**Comment by clovyclov** [comment]
Glad it helped!
