### ISSUE TITLE
[Question] Xamarin Forms - Crop Animation?

### ISSUE THREAD

**Issue by MaxHampton** [martijn00/LottieXamarin#178]
Lottie seems like a fantastic way to integrate detailed animations into a mobile application. I'm trying to work with an indeterminate linear loading animation from www.LottieFiles.com. Here is a link to the animation: https://www.lottiefiles.com/295-refresh. It is a flat and linear animation, but the file as a whole is 600x600. The area I'm interested in rendering on my page is a thin maybe 25-50px horizontal strip in the middle, where the animation is actually happening. How do I crop a Lottie animation to show just the animation without all the padding and white space, or what margin/scale settings work for something like this?

    <StackLayout>
      
      <AnimationView />
      
      <ContentPage.Content />
    </StackLayout>

**Comment by martijn00** [comment]
You can post questions like this on Stackoverflow.

**Comment by RyanGaudion** [comment]
@MaxHampton did you find an answer?
