### ISSUE TITLE
Bug: Weird crash when showing a Lottie animation : "Invalid Layer Save Flag"

### ISSUE THREAD

**Issue by galadril** [martijn00/LottieXamarin#180]
Tested on Pixel 2 with Android P DP3.
I tried to disable hardware acceleration. Didn't help.

The same issue was reported on the lottie-android library:
https://github.com/airbnb/lottie-android/issues/802

I'm getting the next exception:
**Java.Lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed**

### Steps to reproduce :scroll:
1. See isson on lottie-android, there is a animation / code file uploaded there to reproduce this exception
2. Test on a Android P device/emulator

### Expected behavior :thinking:
The animation should work when targetting the new Android P firmware

### Actual behavior :bug:
There is a crash right away

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

Im testing this on a Xamarin Forms projects on an Android device or emulator

**Comment by galadril** [comment]
Seems like it would be fixed if you use the latest aar from android lottie:
https://mvnrepository.com/artifact/com.airbnb.android/lottie/2.5.6

**Comment by martijn00** [comment]
@fabionuno could you make a PR to update the bindings to the latest version to fix this?

**Comment by martijn00** [comment]
Update with 2.6.0 is available on Nuget
