### ISSUE TITLE
Unable to load animation first time (Library)

### ISSUE THREAD

**Issue by SMarconetto** [martijn00/LottieXamarin#183]
### Steps to reproduce :scroll:

1. Create a .NetStandard 2.0 Library (add LottieXamarin NuGet, last version)

2. Create a ContentPage that use a Lottie Animation

3. Add Library to Xamarin.Forms project and use Library Page.

### Expected behavior :thinking:
Animation start first time

### Actual behavior :bug:
Animation is showing only the second time you instance Library page

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

I have attached a sample. 
NOTE: if you press "Play" Visual Studio can give some dependency problem. Clean, restart then compile single DLL in this order: Library, Library.Android, App, App.Android. 

[LottieTest.zip](https://github.com/martijn00/LottieXamarin/files/2323581/LottieTest.zip)

**Comment by luismts** [comment]
The same issue here. The loop animation is not working. Events and commands don't get raised. Any update about this?

UPDATE: Trying to figure out whats happened I set `Speed="10"` and the animation is working too fast around every 10 seconds. But I downloaded it from Lottie web page and it seems to work. I try using another one and the same happens.
