### ISSUE TITLE
AnimationView does not resize

### ISSUE THREAD

**Issue by ChasakisD** [martijn00/LottieXamarin#190]
### Steps to reproduce :scroll:
1. Use this https://www.lottiefiles.com/63-hamburger-arrow-transition lottie file
2. Create an animation view like in the example
```xml
<lottie:AnimationView
        Loop="False"
        AutoPlay="False"
        BackgroundColor="Red"
        VerticalOptions="Center"
        Animation="hamburger_animation.json"
        WidthRequest="60"
        HeightRequest="60" />
```

### Expected behavior :thinking:
The lottie animation should respect the width and the height request.

### Actual behavior :bug:
The view is 60x60 and it is red, but the lottie animation icon is like 15x15.

### Configuration :wrench:

**Version:** 2.6.3

**Platform:** 
- [\] :iphone: iOS 12
- [\] :monkey: Xamarin.Forms 3.2.0.839982

**Comment by OdetteP** [comment]
Did you solve this issue?
