### ISSUE TITLE
unable to install Com.Airbnb.Xamarin.Forms.Lottie 2.6.3

### ISSUE THREAD

**Issue by henryyue2010** [martijn00/LottieXamarin#191]
Hi,
When I tried to install Com.Airbnb.Xamarin.Forms.Lottie 2.6.3. I got following errors:

Could not install package 'Com.Airbnb.Xamarin.Forms.Lottie 2.6.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

How to fix the issue?
Thank you very much.
Henry

**Comment by gvsharma** [comment]
As suggested [here](https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/), you need to update to .Net Standard lib and this can be imported. For me its working with .Net Standard 2.0
