### ISSUE TITLE
Lottie fails to build on tvOS device builds

### ISSUE THREAD

**Issue by ethanis** [martijn00/LottieXamarin#192]
### Steps to reproduce :scroll:

1. Clone this [repro](https://github.com/erdennis13/Lottie.tvOS.Sample)

2. Build for tvOS simulator - no error.

3. Build or tvOS device - build error.

### Expected behavior :thinking:
App should build and deploy for a tvOS device build.

### Actual behavior :bug:
Build is failing due to native linker errors for tvOS device builds.

```
Build FAILED.

MTOUCH : warning MT2107: It's not safe to remove the dynamic registrar, because Lottie.iOS references 'ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate, System.Delegate)'.
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5216: Native linking failed for '/Users/ethand/Desktop/Lottie.tvOS.Sample/Lottie.tvOS.Sample/obj/iPhone/Debug/mtouch-cache/arm64/libLottie.iOS.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com
    1 Warning(s)
    2 Error(s)
```

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [x] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This will be fixed in the next release.

**Comment by jd-alexander** [comment]
Was this resolved?

**Comment by ethanis** [comment]
@jd-alexander looks like it to me, the repro builds successfully now..
