### ISSUE TITLE
PlayProgressSegment not working properly on Xamarin.Forms Android.

### ISSUE THREAD

**Issue by josemmp** [martijn00/LottieXamarin#193]
### Steps to reproduce :scroll:

![image](https://user-images.githubusercontent.com/34225481/47580995-eb4c8000-d915-11e8-983d-e0bca102d9e2.png)

### Expected behavior :thinking:
When the animation reaches 52% of progress it should play reverse and when it gets on the start point (0%) it should play again forward.

### Actual behavior :bug:
First time it goes from 0 to .52, then it backwards from .52 to 0 but after that it continues going from .52 to 0, just in android platform, on iOS its working fine.

### Configuration :wrench:

**Version:** 2.6.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Ghasan** [comment]
I am facing the same issue, though I am not sure about iOS.

Updated: I can confirm it too. It works flawlessly on iOS, only on Android it misbehaves.

**Comment by OdetteP** [comment]
Did you solve this issue?
