### ISSUE TITLE
Cannot access pathForResource from Assets catalog

### ISSUE THREAD

**Issue by Wenfengcheng** [martijn00/LottieXamarin#196]
I also found [the same problem in Airbnb's lottie-ios repo](https://github.com/airbnb/lottie-ios/issues/580). When the animation json file needs to rely on local images, it can't load local images from *Asset Catalogs* or *Local Resources folder*.

Warnings from my project:
```
[LOTLayerContainer _setImageForAsset:]: Warn: image not found: img_1.png
```

*Airbnb's lottie-ios* has fixed this bug and released the latest version 2.5.2, but *LottieXamarin* binding repo did not update the latest sdk.

Please update the latest *lottie-ios 2.5.2* sdk, and release new nuget package.

Thank you!

**Comment by martijn00** [comment]
@fabionuno could you update the iOS binding to 2.5.2? I can release new packages for Forms.

**Comment by fabionuno** [comment]
@martijn00 yes, I can. Maybe I can open a PR today.

**Comment by martijn00** [comment]
The new release is available on nuget!
