### ISSUE TITLE
How could we merge code together?

### ISSUE THREAD

**Issue by kanvuduc** [martijn00/LottieXamarin#20]
Hi @martijn00,

I have also created [Xam Binding for Lottie](https://github.com/NAXAM/xam-binding-lottie). I also migrated fully sample for the iOS part.

I see your code has a lot of things for binding, not that the generated one. It's like craftsmanship.

It would be great if we could merge our code together and together maintain a single code base.

Regards,
Tuyen.

**Comment by martijn00** [comment]
Feel free to create a pull request to add your code. I will add you to the contributors then.

**Comment by modplug** [comment]
@kanvuduc: Your iOS sample could easily be "ported" to this library. I think the best way to merge the two would be to use this binding library as base.
