### ISSUE TITLE
Animation disappears : background and changing animation propery

### ISSUE THREAD

**Issue by vincentcastagna** [martijn00/LottieXamarin#200]
## 🐛 Bug Report

On iOS **AND** Android 
 * When the app goes background, animation disappears.
* When binding AnimationProperty & ImageAssetFolder of the AnimationView and changing it in codeBehind or viewModel, it disappears too and sometimes re-appears and disappears again.

I tried creating a new AnimationView object in the codebehind for the AnimationView object I got on the view, but does not change anything. Bug still occurs. 

Video of  what happens : 

https://youtu.be/i8j1xC0o9gg

### Expected behavior
* When app goes in background and then foreground, animation should always be there.
* When changing AnimationProperty of the AnimationView should still be visible and playing.
* When creating a new AnimationView object with new properties, should also be visible and playing.

### Reproduction steps

1. Instantiate on the view a new AnimationView object with AnimationProperty set and ImageAssetFolder, height, width, AutoPlay = true, Loop = true.
2. Put the app in background and then in foreground

OR

1. Same step
2. Put a button on the view 
3. Register to button event clicked and change AnimationProperty & ImageAssetsFolderProperty in the event.
4. Animation disappears sometimes, sometimes re-appears and then disappears definitely.

### Configuration

* Prism 7.0
* Xamarin Forms 3.2.0.871581
* Lottie Forms 2.6.3

**Platform:** 
- Android Honor 9  Oreo 8.1
- iPhone 5S iOS 12

I think this issue is related to this one : https://github.com/airbnb/lottie-ios/issues/481

EDIT : I just updated to 2.7.0 ... now the animation does not appear AT ALL....

**Comment by vincentcastagna** [comment]
@martijn00 can you check this plz  ?

**Comment by martijn00** [comment]
Try 2.7.1
