### ISSUE TITLE
[Xamarin Forms] Issues with iOS and Android

### ISSUE THREAD

**Issue by adrianknight89** [martijn00/LottieXamarin#202]
## 🐛 Bug Report

On iOS, animations do not play properly. On Android, they do not load at all. Note that the iOS issue seems to happen with specific files as I was able to get other json files to play as expected.

### Expected behavior
Animations should play as expected on both platforms. The attached animation should look like this: https://www.lottiefiles.com/983-rejection

### Reproduction steps
Run the attached repro on iOS and Android

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

[LottieTest.zip](https://github.com/martijn00/LottieXamarin/files/2610926/LottieTest.zip)

**Comment by Azyyyyyy** [comment]
Same here, I tried using older versions but they error out (parsing error)
Tested with Android (9), Pixel 2

**Comment by K232** [comment]
After downgrading Lottie from 2.7.0 to 2.6.3, Android works fine for me, see #204. Maybe this helps?

**Comment by hot33331** [comment]
I tried to get the following running with 2.7.0:

`
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:lottie="clr-namespace:Lottie.Forms;assembly=Lottie.Forms" 
             xmlns:local="clr-namespace:LottieDemo" x:Class="LottieDemo.MainPage">
    
        <StackLayout Spacing="20" Padding="15">
            <lottie:AnimationView 
            x:Name="animationView"
            Animation="LottieLogo1.json" 
            Loop="false" 
            AutoPlay="true" 
            VerticalOptions="FillAndExpand" 
            HorizontalOptions="FillAndExpand" />
        </StackLayout>
   
</ContentPage>
`

It works perfectly on iOS does not show the Animation on Android. When I downgrade to 2.6.3 it works.

**Comment by martijn00** [comment]
Try 2.7.1

**Comment by vincentcastagna** [comment]
@martijn00 just tried 2.7.1, when HorizontalOptions & VerticalOptions are set to "FillAndExpand" animation does not display anymore. Need to set a Width & HeightRequest which brings a non-responsive animation. I'm trying to debug and see what could cause this behavior, seems the containing layout matters.

**Comment by adrianknight89** [comment]
@martijn00 This needs to be re-opened. I tried 2.7.1 and was unable to play https://www.lottiefiles.com/983-rejection properly on iOS. This file works on Android but not iOS.
