### ISSUE TITLE
Couldn't get it to work on Android with Xamarin Forms

### ISSUE THREAD

**Issue by K232** [martijn00/LottieXamarin#204]
## 🐛 Bug Report

I've created a new Xamarin Forms project from Scratch, using latest Xamarin Forms 3.4 and .net standard 2.0.3. Animation works fine on iOS, but is not shown on Android. Might be related to #202 but I don't have problems with iOS.
I've attached a sample app: [LottieTest.zip](https://github.com/martijn00/LottieXamarin/files/2652546/LottieTest.zip)

### Expected behavior
Animation should be shown on Android

### Reproduction steps

1. Create new Xamarin Forms Project
2. Add Lottie to project
3. Add "LottieLogo1.json" to "Assets"-Folder in Android and "Resources" Folder on iOS.
4. Update Mainpage.xaml:

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:lottie="clr-namespace:Lottie.Forms;assembly=Lottie.Forms"
    x:Class="LottieTest.MainPage2">
    <ContentPage.Content>
        <StackLayout BackgroundColor="White">
            <lottie:AnimationView 
                x:Name="animationView" 
                Animation="LottieLogo1.json" 
                Loop="true"
                AutoPlay="true"
                VerticalOptions="FillAndExpand" 
                HorizontalOptions="FillAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
I've also tried `ImageAssetsFolder="Assets"` for testing but no changes.

### Configuration

**Version:** 2.7.0

**Platform:** 
- [x] :robot: Android
- [x] :monkey: Xamarin.Forms

**Comment by K232** [comment]
Update: Problem found. After downgrading to Lottie 2.6.3, animation is displayed on Android as expected.

**Comment by hnabbasi** [comment]
Confirmed. I also had the same issue on Android with `2.7.0`. Downgraded to `2.6.3` and works on both iOS and Android now.

**Comment by hytea** [comment]
I have also confirmed this issue. Downgrading the Android version to `2.6.3` worked for me.

**Comment by sikandaramla** [comment]
Downgrading solved it, Issue closed! Sarcasm....

**Comment by Calinciurariu** [comment]
Baseflow, @sikandaramla  was right, why block him instead of coming with a fix?

**Comment by martijn00** [comment]
@Calinciurariu hateful comments that don't add value to the conversation should be closed. Just as your comment "instead of coming with a fix" is very insulting. Why don't you open a PR yourself? Why don't you pay to fix it?

**Comment by Calinciurariu** [comment]
>"instead of coming with a fix" is very insulting
I am not asking for a fix, just that censorship is not the right way.
>Why don't you pay to fix it?
What is your business model? Isn't it free of charge for small companies/demos/people who are just starting AND THEN they pay as they generate income? If you can't attract me why would I buy the product?

I'm only trying to help here, don't consider anything insulting as it just plainly isn't.

**Comment by finebytes** [comment]
If it helps anybody, I managed to get it working by setting the Target Android Version to 10.0
![image](https://user-images.githubusercontent.com/595559/85806135-e1b49480-b756-11ea-8371-f5883e61e734.png)

Just make sure you clean build it, uninstall it from the device and publish it fresh if it doesn't work the first time.
