### ISSUE TITLE
lottie.forms.droid not available in lottie 2.7.1

### ISSUE THREAD

**Issue by technololy** [martijn00/LottieXamarin#208]
## 🐛 Bug Report

lottie.forms.droid not available in the droid aspect of xamarin, hence the AnimationViewRenderer is unusable and you can not in itialize it in the droid
### Expected behavior
lottie.forms.droid be available in the droid aspect of xamarin, hence the AnimationViewRenderer be initialized
### Configuration
Xamarin forms 3.4
**Version:** 1.x
version 2.7.0
**Platform:** 

- [ ] :robot: Android

**Comment by Alibesharat** [comment]
I had this problem too

**Comment by technololy** [comment]
i had to downgrade
