### ISSUE TITLE
The type or namespace name 'Droid' does not exist in the namespace 'Lottie.Forms' in version 2.7.0

### ISSUE THREAD

**Issue by RadoslawKubas** [martijn00/LottieXamarin#210]
## 🔙 Regression

After update to 2.7.0 version error appear

> Error | CS0234 | The type or namespace name 'Droid' does not exist in the namespace 'Lottie.Forms'

so can't initialise renderer

> Error | CS0103 | The name 'AnimationViewRenderer' does not exist in the current context 

### Old (and correct) behavior

Application builds and works fine when using 2.6.3 version.

### Current behavior

Can't build application.

### Reproduction steps

Crete basic Xamarin.Forms Android app and initialization code to MainActivity

`using  Lottie.Forms.Droid;`

`AnimationViewRenderer.Init();`

### Configuration

**Version:** 2.7.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by erlandvr** [comment]
I fixed it by updating the targetFramework in source/Droid/packages.config.

 `<package id="Com.Airbnb.Xamarin.Forms.Lottie" version="2.7.0" targetFramework="monoandroid90" />`

**Comment by RadoslawKubas** [comment]
Thank you for a hint, but unfortunately my project is using "PackageReference" format and everything there seems to be fine.

```
<PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
 <Version>2.7.0</Version>
</PackageReference>
```

Do you have any idea how to fix it there?

**Comment by roubachof** [comment]
I fixed it by simply changing the android sdk version to 9 in the csproj of the android project.

**Comment by RadoslawKubas** [comment]
@roubachof Thank you a lot, it works now.
