### ISSUE TITLE
Xamarin.Forms UWP exception using Pagerenderer

### ISSUE THREAD

**Issue by EmilAlipiev** [martijn00/LottieXamarin#211]
## 🐛 Bug Report

if i use pagerenderer just like below in uwp, lottie is throwing exception as 

```
  at Lottie.Forms.UWP.Renderers.AnimationViewRenderer.<OnElementChanged>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

```
```
public class ContentPageRenderer : PageRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.Page> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null || Element == null)
            {
                return;
            }

            ContentPage page = ((ContentPage)Element);
            if (page.Content == null )
                return;

            var XboxControls = new MyUserControl1();
            StackLayout stackLayout = new StackLayout() { Orientation = StackOrientation.Vertical };
            stackLayout.Children.Add(page.Content);
            stackLayout.Children.Add(XboxControls.ToView());

            page.Content = stackLayout;
        }

    }
```
 
### Reproduction steps

1. run attached test project in UWP local, you will see that lottie will throw exception.
2. remove ContentPagerenderer class and run it again it works.

 
**Version:** 1.x
2.7
**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

[App3.zip](https://github.com/martijn00/LottieXamarin/files/2857605/App3.zip)

**Comment by EmilAlipiev** [comment]
Another sample project to make the problem clearer. if you run the project attached below, you can see that if i use any custom renderer on the same page as AnimationView is implemented it will throw exception. if you go to itemspage in the sample and comment out Xboxview, you will see that no exception is thrown. if you move all initialization from onAppearing to constructor also work. maybe it is not optimal implementation but it is supposed to working without any exception.

[App3.zip](https://github.com/martijn00/LottieXamarin/files/2863273/App3.zip)

**Comment by EmilAlipiev** [comment]
Is that project abandoned? I am seeing crashes on UWP. It seems that this exception in the attached project occurs even for different reasons.

**Comment by azchohfi** [comment]
It has been superseded by a native Microsoft official version. We need to update LottieXamarin to use this new version.
https://github.com/windows-toolkit/Lottie-Windows

**Comment by vincentcastagna** [comment]
@azchohfi

Great news. Any roadmap planned?

**Comment by sohchatt** [comment]
@martijn00 what are the requirements for using [Lottie-Windows](https://aka.ms/lottie) in LottieXamarin? What is the OS version support policy for LottieXamarin on Windows 10 (Note: Lottie-Windows depends on Windows 10 SDK 17763)? If this is an issue for the near-term, perhaps we can use a versioning approach to switch on up-level versions in LottieUWP, @azchohfi ?

**Comment by azchohfi** [comment]
@sohchatt AFAIK, there is none. Since LottieUWP supported all the way back to TH2, this will be a breaking change, for sure, but it's the only way forward. It should support whatever Lottie-Windows supports.
As for the up-level support, I don't have the numbers to support this. Let's sync offline.

**Comment by martijn00** [comment]
@sohchatt @azchohfi i'm happy to take PR's for the update.
