### ISSUE TITLE
Animation doesn't show properly on Xamarin.iOS

### ISSUE THREAD

**Issue by papafe** [martijn00/LottieXamarin#214]
## 🐛 Bug Report

Animation doesn't show properly on Xamarin.iOS

### Expected behavior

The animation on iOS should show the same as in the demo.html file. 

### Reproduction steps

I am loading the animation with a very simple code:

           
            animation = LOTAnimationView.AnimationNamed("splash");
            animation.ContentMode = UIViewContentMode.ScaleAspectFill;
            animation.TranslatesAutoresizingMaskIntoConstraints = false;
            animation.LoopAnimation = true;
            View.AddSubview(animation);

            View.AddConstraints(new NSLayoutConstraint[]
            {
                animation.BottomAnchor.ConstraintEqualTo(View.BottomAnchor),
                animation.TopAnchor.ConstraintEqualTo(View.TopAnchor),
                animation.LeftAnchor.ConstraintEqualTo(View.LeftAnchor),
                animation.RightAnchor.ConstraintEqualTo(View.RightAnchor),

            });

Here you can see the comparison of the html animation, and the iOS one: [lottie.zip](https://github.com/martijn00/LottieXamarin/files/2988357/lottie.zip)

**Version:** 2.5.7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Not everything is supported on mobile. Please open an issue at the Airbnb repo.
