### ISSUE TITLE
AnimationViewRenderer cannot be called, namespace cannot be found

### ISSUE THREAD

**Issue by MaxenceMax** [martijn00/LottieXamarin#216]
## 🐛 Bug Rport

AnimationViewRenderer cannot be called on android platform, namespace cannot be found.
### Expected behavior
Display animation on Android platform.
### Reproduction steps
--> Dowload latest android sdk version (9.0)
--> Install Lottie nugget package (latest version)
--> Try to call AnimationViewRenderer.Init in MainActivity
### Configuration
Visual Studio Mac 
Android SDK 9.0
Xamarin forms 3.6

**Version:** 2.7.1 

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by mrxten** [comment]
@martijn00 why you closed issue without any comment? I have same problem.

**Comment by ghost** [comment]
Got same problem as well. Issue has not been fixed.
