### ISSUE TITLE
Use latest Microsoft `Lottie-Windows` toolkit for Windows renderer

### ISSUE THREAD

**Issue by hinterlandcreative** [martijn00/LottieXamarin#218]
## 🚀 Feature Requests

Remove usage of `LottieUWP` (which has issues) and use latest Lottie controls from Microsoft: [Microsoft.Toolkit.Uwp.UI.Lottie](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.UI.Lottie/) ([github repositiory](https://github.com/windows-toolkit/Lottie-Windows)) which uses the Composition Layer to render the animation.

### Contextualize the feature

This would affect the UAP renderer.
### Describe the feature

See Summary.

### Platforms affected (mark all that apply)
- [x] :monkey: Xamarin.Forms
- [x] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :apple: MacOS
- [ ] :tv: tvOS

**Comment by pmorris-dev** [comment]
This would be great since we are getting native crashes with LottieUWP.

**Comment by hinterlandcreative** [comment]
> This would be great since we are getting native crashes with LottieUWP.

Agreed!! I am seeing COM Exceptions and Graphics Canvas crashes with `LottieUWP`, even after proper disposal of the resources (which requires 6 separate methods to be called)

``` CSharp
            AnimationView.InvalidateSelf();
            AnimationView.CancelAnimation();
            AnimationView.RemoveAllAnimatorListeners();
            AnimationView.RemoveAllLottieOnCompositionLoadedListener();
            AnimationView.RemoveAllUpdateListeners();
            AnimationView.Dispose();
```

**Comment by azchohfi** [comment]
@sohchatt should be able to help.

**Comment by velocitysystems** [comment]
Indeed, we need this too!

**Comment by hinterlandcreative** [comment]
> @sohchatt should be able to help.

Thanks @azchohfi ! 

P.S. - Regardless of this request, will there be an update to or ongoing support for `LottieUWP`? We can ticket up some reproducible bugs over there if there will be updates.

**Comment by azchohfi** [comment]
I'm not planning on pushing a new version. Unfortunately, I don't have the bandwidth to invest in it anymore. This project (LottieUWP) was built to fill the gap that the platform (Windows) did not support back then, but now we have a whole team that built and support this new version, which is much more performant and elegant.
Still, I would accept PRs that fixes things, and as long as it does not break API signatures, if you build it by your self, you can still use this version without rebuilding LottieXamarin.

**Comment by hinterlandcreative** [comment]
@azchohfi I think we will wait on a renderer which uses Lottie-Windows or build our own renderer in the meantime.

**Comment by martijn00** [comment]
I would accept a PR for this.

**Comment by hinterlandcreative** [comment]
@martijn00 Unfortunately the `Lottie-Windows` implementation is significantly different enough from the iOS and Android implementations that I don't think you'd accept a PR for this right now. 

For instance, there is no access to frame based playing or a way to see how many frames are in an animation. I've [added a suggestion to the Lottie-Windows repo](https://github.com/windows-toolkit/Lottie-Windows/issues/100) requesting they expose the frame count so at least frame based playing requests can be converted to progress based playing, but no response yet. Until that is resolved you'll have reduced functionality on the UWP renderer...

**Comment by hinterlandcreative** [comment]
Also it requires `1809` to be the minimum & target windows version, so it's going to exclude a lot of legacy users. We decided to punt on bringing in the Microsoft version and are working on a fix for the crashes in `Lottie-UWP`.

**Comment by sohchatt** [comment]
@hinterlandsupplyco we're certainly committed to help achieve parity so you can use Lottie-Windows with Xamarin. As such, FrameCount (and other metadata needed from the JSON) will be exposed in the next update to Lottie. Also, with WinUI 3.0, Lottie-Windows will be able to run on all versions of Windows: here's a preview (27:30 at https://mybuild.techcommunity.microsoft.com/sessions/77008).

**Comment by hinterlandcreative** [comment]
> Also, with WinUI 3.0, Lottie-Windows will be able to run on all versions of Windows..

@sohchatt That's great news!!! That's fixes a big deal breaker for `Lottie-Windows`. Tremendous news.

**Comment by vincentcastagna** [comment]
Any news regarding this ? UWP rendering has clearly a memory leak as of today. Uses 100% of my graphic processor (and my lottie files are optimised, working really well on iOS/Android), which means totally impossible to use.
