### ISSUE TITLE
 java.lang.IllegalStateException: Missing values for keyframe

### ISSUE THREAD

**Issue by tsantinho** [martijn00/LottieXamarin#219]
java.lang.IllegalStateException: Missing values for keyframe.
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.animation.keyframe.ScaleKeyframeAnimation.getValue(ScaleKeyframeAnimation.java:16)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.animation.keyframe.ScaleKeyframeAnimation.getValue(ScaleKeyframeAnimation.java:9)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.getMatrix(TransformKeyframeAnimation.java:118)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:199)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.widget.ImageView.onDraw(ImageView.java:1458)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20499)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.buildDrawingCacheImpl(View.java:19712)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.buildDrawingCache(View.java:19566)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20219)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19301)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20227)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.draw(View.java:20502)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.android.internal.policy.DecorView.draw(DecorView.java:907)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.View.updateDisplayListIfDirty(View.java:19310)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:729)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:735)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:850)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3370)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2701)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.Choreographer.doCallbacks(Choreographer.java:885)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.Choreographer.doFrame(Choreographer.java:809)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.os.Handler.handleCallback(Handler.java:891)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.os.Looper.loop(Looper.java:207)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at java.lang.reflect.Method.invoke(Native Method)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
04-05 20:05:57.906 E/AndroidRuntime( 6981): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

[loadingSample.zip](https://github.com/martijn00/LottieXamarin/files/3049369/loadingSample.zip)

**Comment by tsantinho** [comment]
This error is under Xamarin Forms version 3.6.0.293080 and Lottie 2.7.1

**Comment by Hakim83** [comment]
I have exactly the same problem, while it works well with official app, some animation throw this exception in my app

**Comment by Hakim83** [comment]
trying to rerun the animation in android studio with Lottie 2.7.0 got the same exception, but upgrading to Lottie 3.0.0 works flawlessly.
I hope this new .aar could be successfully bound to project

**Comment by martijn00** [comment]
3.0 can only be updated when Xamarin releases AndroidX support. See https://github.com/martijn00/LottieXamarin/issues/221

**Comment by K232** [comment]
If anyone else is also running into this problem: It's also related to the animation, at least in my case. Replacing the animation with another one fixed the problem (using Lottie 2.6.3).

**Comment by chenjindiao** [comment]
com.airbnb.lottie.parser.KeyframeParser
![image](https://user-images.githubusercontent.com/37047313/59103527-b69baf00-8961-11e9-8b41-fe62ded4717d.png)
