### ISSUE TITLE
When I try to add Com.Airbnb.Xamarin.Lottie to my PCL

### ISSUE THREAD

**Issue by ryanherman** [martijn00/LottieXamarin#22]
I have Xamarin.Forms added already.  Not sure why its complaining?

Installing Com.Airbnb.Xamarin.Forms.Lottie 1.0.0.5.
Install failed. Rolling back...
Package 'Com.Airbnb.Xamarin.Forms.Lottie.1.0.0.5 : Xamarin.Forms [2.3.3.180, )' does not exist in project 'oneiota'
Package 'Com.Airbnb.Xamarin.Forms.Lottie.1.0.0.5 : Xamarin.Forms [2.3.3.180, )' does not exist in folder 'C:\Users\ryan\Dropbox\Programming\oneiota\packages'
Could not install package 'Com.Airbnb.Xamarin.Forms.Lottie 1.0.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by martijn00** [comment]
And do you have Xamarin Forms 2.3.3.180 installed?

**Comment by ryanherman** [comment]
I sure do!

**Comment by gitizenme** [comment]
👍 same issue here as well...

**Comment by ryanherman** [comment]
Yes, I did the same, I installed the iOS and Android version then copied the Renderer's over and it works.

**Comment by ryanherman** [comment]
I just tried creating a new project and adding it, same failed install.

**Comment by martijn00** [comment]
It appeared that the PCL profile in the nuspec was not compatible with Profile111 which is standard used in Forms. I used Profile7 which worked perfectly fine. This is updated now, and it is possible to use in the latest release.
