### ISSUE TITLE
Convert Lottie/json  to gif/video

### ISSUE THREAD

**Issue by leroygumede** [martijn00/LottieXamarin#222]
Any chance is there a way with the current lottie to convert a lottie animation/json to gif in xamarin forms ?

I'm planning to dynamically edit the json and hopefully create a gif from it ?

I tried following an existing tutorial but a lot of code is missing :( 
[How to generate videos using Lottie in Android](https://engineering.21buttons.com/how-to-generate-videos-using-lottie-in-android-2db6ecceb2a)

**Comment by LuckyShine001** [comment]
Did you find any solution?
I need to convert Lottie json to gif. please help me if you have found any solution
Thanks

**Comment by leroygumede** [comment]
@LuckyShine001 , unfortunately no.

**Comment by OdetteP** [comment]
This is not supported by this library, sorry.

**Comment by lilas-dev** [comment]
If you want find tools do this, you can try [this](https://lilas-dev.github.io/lottie2gif/)
