### ISSUE TITLE
Bug : LottieAnimation in Xamarin.Forms using images support 

### ISSUE THREAD

**Issue by KhelifaSaifEddine** [martijn00/LottieXamarin#226]
## 🐛 Bug Report

I have a project with A button in the first page and that button navigate to a second page where my Lottie animation exists, the Lottie animation is a custom animation made by me with after effects
the problem is when I click for the first time on the button, the animation displays normally but when I came back to the main page and re-Click the navigation button to the animation page, I can't find my images

### Reproduction steps
the project  in mediafire : 
https://www.mediafire.com/file/52mm5ladoef2oqt/App14.zip/file
the sample code : https://github.com/KhelifaSaifEddine/Lottie-Animation
### Configuration
Lottie : 2.6.3

**Version:** 1.x

**Platform:** 
- [*] :iphone: iOS
- [

*] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Please put the sample code in a public github repo.

**Comment by FluentGuru** [comment]
I'm looking for something similar, it would be great to have a renderer for Xamarin forms :)

**Comment by KhelifaSaifEddine** [comment]
https://github.com/KhelifaSaifEddine/Lottie-Animation @martijn00  sorry this is the sample code, Sir 
just to make you remember that the problem appears when you back to the button page(main page) and re-click the button to navigate another time to the animation page then you will find that the images disappear

**Comment by OdetteP** [comment]
Did you solve this issue?
