### ISSUE TITLE
Xamarin Forms - Lottie animation freeze after scroll in list view

### ISSUE THREAD

**Issue by KWJ1019** [martijn00/LottieXamarin#228]
## 💬 Questions and Help
Hi.
In my PCL project, I had a list view with data template and have Lottie animation inside the data template. I set the animation loop=True, and AutoPlay= True. When I enter the page, the animation work fine. The issue is when I scroll up and down list view, the animation will freeze and it won't play again. This issue only happen on Android, but iOS worked fine. My caching strategy for list view is set to recycle element.

**Comment by ceburo** [comment]
Hi @martijn00 How do you fix that (which commit,...) ? Have the same problem here.

**Comment by stepkillah** [comment]
Any solution for this one in Xamarin.Forms ?
