### ISSUE TITLE
Xamarin.Android: how to display animation for an async Task?

### ISSUE THREAD

**Issue by pcdus** [martijn00/LottieXamarin#230]
Hello,

I need to display an animation from an `async Task`, that is **triggered** through a `ReverseAsyncCommand` from the **ViewModel**.

On **iOS**, this works fine by using a `TaskCompletionSource` and the `CompletionBlock` property:

    var tcs = new TaskCompletionSource<bool>();
    _lottieCheck.CompletionBlock = (animationFinished) => tcs.SetResult(true);
    _lottieCheck.Play();
    await tcs.Task;
 
On **Android**, I tried to managed this through the `AnimationEnd` event, but this doesn't work:

    _lastStepAnimationView.SetAnimation("animation_check.json");
    _lastStepAnimationView.Animation.AnimationEnd += Animation_AnimationEnd;
    _lastStepAnimationView.Visibility = ViewStates.Visible;
    _lastStepAnimationView.PlayAnimation();

After having setted the animation with `SetAnimation`, the `Animation` property of `_lastStepAnimationView` is still `null`, so the `AnimationEnd` event occurs an Exception.

**_Is it normal? Is there another way to achieve this?_**

**Comment by OdetteP** [comment]
Is this still an issue or fixed with new version?
