### ISSUE TITLE
[Xamarin.Forms] Animation does not render properly on iOS

### ISSUE THREAD

**Issue by adrianknight89** [martijn00/LottieXamarin#233]
Please run the attached repro and observe that the animation does not render properly on iOS whereas Android works fine. I'd like to know why this is the case so that we can create a PR to fix it.

[LottieTest - updated.zip](https://github.com/martijn00/LottieXamarin/files/3326432/LottieTest.-.updated.zip)

**Comment by Near0ne** [comment]
Hi ! :D 
It seems if i'm not wrong, you forgot to add "AnimationViewRenderer.Init();" in the AppDelegate.cs file to use Lottie on iOS (in the FinishedLaunching() function).

More, check your animation, sometimes, on iPhone, animations may be too large for the iPhone screens, for exemple, yours 1080 x 1080 is kinda big.
If you can, reduce it to ~400, animations are made vectorially, so no worry about the quality.

Tell me if you have fixed it :) 

Good luck !

**Comment by adrianknight89** [comment]
@Near0ne My original project had the Init() call, but the issue was still present. I just updated the repro and added that line. Thanks!

As for the size, I have many 1080 x 1080 animations that play perfectly fine on different iPhone models, so I don't think the issue has to do with size.

**Comment by adrianknight89** [comment]
@Near0ne I think I'm going to have to stop using LottieXamarin since the differences between iOS and Android are killing me. :) I just tested out https://github.com/LottieFiles/lottie-player and it's working great!!

**Comment by martijn00** [comment]
The differences is because it is 2 different render engines. If you use the web version it is only 1. The swift rewrite they did was supposed to make it better but Xamarin doesn't support it properly.

**Comment by adrianknight89** [comment]
@martijn00 Thank you, Martijn. That's what I thought. I'm hoping Xamarin can support it better in the future. Thanks for your work on getting this library out there for Xamarin folks. :)
