### ISSUE TITLE
Xamarin.Froms.Lottie doesn't work on Android after upgrade to 2.7 or 3.0

### ISSUE THREAD

**Issue by Maxima078** [martijn00/LottieXamarin#237]
## 🐛 Bug Report

Hi, after upgrading from Xamarin.Forms.Lottie 2.6.x to 3.0 AnimationViews stop working in Android. It works fine in iOS.
I tried making a new project with Xamarin.Froms 4.1.x (latest stable) which is the version I use in my project and couldn't reproduced the bug.
I found this [issue](https://forums.xamarin.com/discussion/144320/lottie-in-xamarin-forms-android) and this [one](https://github.com/martijn00/LottieXamarin/issues/234).
Rolling back to 2.6 fix this issue in my project.

Is there any Android dependencie I'd have missed to be able to upgrade to 2.7 or 3.0?

Thank you.
### Expected behavior
Should work on Android after upgrade to 2.7 or 3.0
### Reproduction steps
* upgrade Xamarin.forms from 3.6 to 4.1 and Lottie from 2.6 to 3.0
### Configuration
Tested over several Android devices/version
**Version:** 3.0 and 2.7 concerned

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Maxima078** [comment]
Switching `Target Framework` to 9.0 fixes this issue. I'm wondering whether it's an expected behaviour?

**Comment by martijn00** [comment]
Yes this is expected.
