### ISSUE TITLE
Lottie file in splash screen ios-android is this possible

### ISSUE THREAD

**Issue by developer9969** [martijn00/LottieXamarin#238]
Hi
As anybody successfully implemented lottie as splash screen in iOS Xamarin Forms?

Android seems possible but I cannot make it work with iOS.
Any example anywhere that works?

Many thanks

**Comment by MSiccDev** [comment]
I have made it working with an extended lock screen (show modal page after native splash finishes).

**Comment by developer9969** [comment]
@MSiccDev thanks for your reply. Can you share sample? Just want to see how it looks.
I did find an article that a guy made it work but it crashes on me see my edited question

**Comment by developer9969** [comment]
@martijn00  pity got closed. Really stuck on ios on  this one. I would have a really nice touch to have lottie in the splash screen.

Pity
