### ISSUE TITLE
animationView.Loop() method is Deprecated

### ISSUE THREAD

**Issue by Alibesharat** [martijn00/LottieXamarin#239]
Why animationView.Loop() method is Deprecated  on :
Com.Airbnb.Android.Lottie v3.0.4
and what is the instead of?
I set the animationView.RepeatCount = int.MaxValue;
is it correct ? And it doesn't make memory leak?

**Comment by OdetteP** [comment]
Is this still an issue or fixed with new version?

**Comment by IeuanWalker** [comment]
@OdetteP The loop property is removed altogether, is the workaround to set int.MaxValue on the repeat count?

**Comment by IliaGrona** [comment]
RepeatMode="Infinite"
