### ISSUE TITLE
Lottie.iOS.dll blocked by COMODO Internet Security

### ISSUE THREAD

**Issue by amironline** [martijn00/LottieXamarin#242]
Hello,

I installed version 3.0.1 of Com.Airbnb.Xamarin.Forms.Lottie in Xamarin forms.
Unfortunately, Lottie.iOS.dll blocked by COMODO Internet Security.
It detected Application.Win32.DomaIQ.KKM@314592350 and quarantine this file.

**Comment by martijn00** [comment]
Fill out a proper issue
