### ISSUE TITLE
Animation not playing on XF Android platform

### ISSUE THREAD

**Issue by Arieldelossantos** [martijn00/LottieXamarin#244]
## 🐛 Bug Report

Animation not playing

### Expected behavior
 It should play on both platform in a XF project

### Configuration
Set the animation to isPlaying=true

**Version:** 3.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Please provide better information or a reproduction case
