### ISSUE TITLE
The namespace Lottie.Forms.Droid is not found.

### ISSUE THREAD

**Issue by iamheiner** [martijn00/LottieXamarin#246]
## 🐛 Bug Report

Error when importing Lottie into Xamarin Forms Android. The namespace Lottie.Forms.Droid is not found.

Error when initializing `AnimationViewRenderer.Init();` on 

### Reproduction steps
1. Create an application of Xamarin Forms V4
2. Install package nuget Com.Airbnb.Xamarin.Forms.Lottie
3. In the OnCreate method of MainActivity I add AnimationViewRenderer.Init();
4. Add the lottie json file to the Android project in the Assets folder of the Android project
5. Add `xmlns:lottie="clr-namespace:Lottie.Forms;assembly=Lottie.Forms"` in the header of the Xaml page where I'm going to run it
6. Add the code 
 `<lottie:AnimationView
     x:Name="LottieView"
    Animation="file.json" 
     VerticalOptions="FillAndExpand"
     HorizontalOptions="FillAndExpand" />`

### Configuration

Xamarin Forms **Version:** 4.2.0
Com.Airbnb.Android.Lottie **Version:** 3.0.3

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by Firice** [comment]
I same issue, can't install Com.Airbnb.Android.Lottie 3.0.5.
`Could not install package 'Com.Airbnb.Android.Lottie 3.0.5'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v8.1'`

**Comment by OdetteP** [comment]
I reproduced every step but here it works fine.

**Comment by martijn00** [comment]
Use Android 9.0
