### ISSUE TITLE
Upgrade Lottie Android to 3.4.0

### ISSUE THREAD

**Issue by 4brunu** [martijn00/LottieXamarin#247]
## 🚀 Feature Requests

Hey, thanks for this lib 🙂 

Can you please upgrade Lottie Android to [3.4.0](https://github.com/airbnb/lottie-android/releases/tag/v3.4.0)?

Thanks

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by 4brunu** [comment]
@martijn00 now that AndroidX is stable on Xamarin, do you think that now it will be easier to update to the last version of Lottie?
https://www.nuget.org/packages?q=androidx

**Comment by martijn00** [comment]
Done

**Comment by 4brunu** [comment]
Thanks 👍
