### ISSUE TITLE
[Bug]Animation view freezes in CarouselView (Android only)

### ISSUE THREAD

**Issue by denzerd** [martijn00/LottieXamarin#249]
## 🐛 Bug Report
When the AnimationView is placed as an element within a CarouselView, the AnimationView will stop animating when swiping to the next (or previous) slide. When coming back to the stopped slide, the animation does not continue. 
It looks like a freeze of the Animation.
This is seen only in Android, iOS is working just fine.

### Expected behavior
Either the same as in iOS where the Animation just finishes or the animation should continue once coming back to the stopped slide (First solution preferred) 

### Reproduction steps
Place a AnimationView within a CarouselView. Giving it a longer animation makes it easier to reproduce. Once the AnimationView starts animating, swipe to the next (or previous) slide. Go back to the slide with the animating view. The animation will be frozen. (Android only)

### Configuration

**Version: 3.0.3

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

### Reproduction Repo
I created a super simple project for you which you can just start up on an Android phone. You will see the issue.

[LottieCarousel.zip](https://github.com/Baseflow/LottieXamarin/files/3931089/LottieCarousel.zip)

**Comment by noushavandijk** [comment]
Same issue here

**Comment by InquisitorJax** [comment]
This seems to be fixed with the latest release - at least for me it is :)

**Comment by martijn00** [comment]
Try 4.0
