### ISSUE TITLE
Animation not playing after navigating back from different page

### ISSUE THREAD

**Issue by eliasehmann** [martijn00/LottieXamarin#254]
## 🐛 Bug Report

The animation is not playing when you navigate back to the Page, after you've been to another, even if _IsPlaying_ is set to _true_.

### Expected behavior
The animation should be freezes at the last frame or start all over again.

### Reproduction steps
Navigate to new page and navigate back to page with AnimationView after that.

### Configuration
<forms1:AnimationView  Grid.Row="1" Animation="animation.json"
                                   Loop="false"
                                   VerticalOptions="FillAndExpand"
                                   IsPlaying="true"
                                   Speed="1">
  </forms1:AnimationView>

**Version:** 3.0.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms
only tested on UWP

**Comment by KSemenenko** [comment]
I will check it

**Comment by eliasehmann** [comment]
@KSemenenko did you check?
