### ISSUE TITLE
[UWP] Lottie Animations no longer rendering at version 3.0.4

### ISSUE THREAD

**Issue by MattRames** [martijn00/LottieXamarin#255]
## 🐛 Bug Report

Lottie animations don't seem to render on Xamarin.Forms UWP at package version 3.0.4.

Likely related to https://github.com/Baseflow/LottieXamarin/pull/253 

### Expected behavior
I expect to see a lottie animation.

### Reproduction steps
Load the sample app for UWP forms and see that there is no animation. 

![image](https://user-images.githubusercontent.com/9450530/74287290-3945ec80-4cef-11ea-9137-e60e802fb810.png)

### Configuration

**Version:** 3.0.4

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by KSemenenko** [comment]
I will check it

**Comment by fabien367** [comment]
I have the same problem

**Comment by KSemenenko** [comment]
it's all about Lotttie for UWP.
still working on it.

**Comment by GuidoNeele** [comment]
Any news?

**Comment by a-iafrate** [comment]
same problem for me, please fix it!

**Comment by jamesmcroft** [comment]
Looking into this issue now and I think I might have fixed it. Just need to do some more testing.

**Comment by sjorsmiltenburg** [comment]
I just upgraded a project with a working animation (old version xamarin forms and lottiexamarin) to the latest lottie version v3.1.2 and latest Xamarin.Forms to see if UWP rendering was fixed after this patch was merged. I failed to see an animation after the upgrade. Is there a working XF.UWP sample app that works with this new version? Maybe I'm missing additional requirements like intialisation or something.

**Comment by MattRames** [comment]
@sjorsmiltenburg The animation in the [sample app](https://github.com/Baseflow/LottieXamarin/tree/develop/Samples/Forms) works; however, when I upgraded in my application my animations still didn't show. After investigating it seems like I needed to bump my minimum and target windows version. 

![image](https://user-images.githubusercontent.com/9450530/81580108-9dba2b80-9372-11ea-9d86-478fe2c48091.png)

However things still seem a bit weird. For example the following AnimationView doesn't actually play the animation. #270 

```
<forms:AnimationView x:Name="animationView"
                     Grid.Row="1"
                     Animation="LottieLogo1.json"
                     HorizontalOptions="FillAndExpand"
                     IsPlaying="True"
                     Loop="True"
                     VerticalOptions="FillAndExpand" />
```
I'm also having trouble getting PlayFrameSegment or PlayProgressSegment to work unless it's in reverse. #269 
```
playSegmentsButton.Clicked += (sender, e) =>
{
    animationView.PlayProgressSegment(0.65f, 1.0f); // Doesn't animate
    //animationView.PlayProgressSegment(0.65f, 0.0f); // Animates
};
playFramesButton.Clicked += (sender, e) =>
{
    animationView.PlayFrameSegment(50, 100); // Doesn't animate
    //animationView.PlayFrameSegment(50, 1); // Animates
};
```

**Comment by sjorsmiltenburg** [comment]
Thx for creating the 2 new bugs. I tried bumping the target/minimum version in my sample app but no success. Your not working code sample #270 also does not differ from the sample app as far as I can see. Not using bindings would be a weird cause but hey.. we'll see.

**Comment by MattRames** [comment]
When starting an animation with a binding the animation starts from OnElementPropertyChanged
```
else if (e.PropertyName == AnimationView.IsPlayingProperty.PropertyName && !string.IsNullOrEmpty(Element.Animation))
{
    if (Element?.IsPlaying == true)
    {
        Play();
    }
    else
    {
        _animationView?.Pause();
    }
}
```
When just setting it to True it starts from OnElementChanged
```
#pragma warning disable CS0618 // Type or member is obsolete
                if (e.NewElement.AutoPlay || e.NewElement.IsPlaying)
#pragma warning restore CS0618 // Type or member is obsolete
                {
                    _ = _animationView.PlayAsync(0, 1, e.NewElement.Loop).AsTask();
                }
```

Not sure why it matters, but I assume something just isn't setup quite right at the beginning.

**Comment by jamesmcroft** [comment]
I can take a look into that again :) I think I know what's causing it in your scenario.

**Comment by Kbmobi** [comment]
Any resolution to this? 
I still can not get Lottie files to run in UWP. Android and iOS are perfectly fine.

**Comment by afernandes** [comment]
Any resolution to this?
