### ISSUE TITLE
Animation stops too early on iOS

### ISSUE THREAD

**Issue by eliasehmann** [martijn00/LottieXamarin#258]
## 🐛 Bug Report

The animation stops to early on iOS. Some last frames don't get displayed properly.

### Expected behavior

The animation plays till last frame.

### Reproduction steps

use any animation which has some visual changes between the last few frames

Version: 3.0.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [x] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by linuskirschbaum** [comment]
Same issue .......

**Comment by winterdouglas** [comment]
I'm facing this issue too, tested with the latest versions yesterday. Android with the same animation works nicely.
