### ISSUE TITLE
Lottie for Xamarin.Forms animations do not load under version 3.1

### ISSUE THREAD

**Issue by steffenSuess** [martijn00/LottieXamarin#260]
## 🐛 Bug Report

Hey, I updated LottieXamarin in some of my Xamarin.Forms Projects from 3.0.3 to 3.1 and since that in none of them the Lottie-Files are displayed or playing on Android. --> Downgraded to 3.0.3 and all works fine. 

### Expected behavior
Loading and Playing Animations

**Version:** 3.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Update to Android 10
