### ISSUE TITLE
3.1.0 Com.Airbnb.Xamarin.Forms.Lottie not working

### ISSUE THREAD

**Issue by halotron** [martijn00/LottieXamarin#261]
## 🐛 Bug Report

3.0.4 works for xamarin forms on android, but 3.1.0 does not.
### Expected behavior
Only background is painted. No animation.
### Reproduction steps
new xamarin forms. Create view with this and have file in assets.
                <forms:AnimationView IsVisible="{Binding IsBusy}" 
                                     x:Name="animationView" 
                                     Animation="51_preloader.json" 
                                     Loop="true" 
                                     AutoPlay="True"
                                     VerticalOptions="FillAndExpand" 
                                     HorizontalOptions="FillAndExpand"
                                     IsPlaying="{Binding IsBusy}" />
### Configuration

**Version:** 3.1.0

**Platform:** 
- [ ] :iphone: iOS
- [ X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Logikoz** [comment]
up
