### ISSUE TITLE
AnimationViewRenderer.Init() not found in 3.1.0

### ISSUE THREAD

**Issue by dalton5** [martijn00/LottieXamarin#262]
Hi,

I use version 3.1.0.

I try to initialize AnimationViewRenderer.Init() but I can't find the Namespace and AnimationViewRenderer. 

Is it a regression?

Thanks,

**Comment by martijn00** [comment]
Use Android 10

**Comment by dalton5** [comment]
Thanks. If I want to use Android 9.0 which version should I use of Lottie Forms?
