### ISSUE TITLE
Upgrade Lottie for XF

### ISSUE THREAD

**Issue by shira164** [martijn00/LottieXamarin#264]
## 🔙 Regression

After updating the "Com.Airbnb.Xamarin.Forms.Lottie" nugget from version 3.0.4 to version 3.1.0 it has stopped showing animation on Android

### Old (and correct) behavior

In version 3.0.4 it correctly showed animation

### Current behavior
Doesn't show animation on Android

### Reproduction steps
1.- Create a project Xamarin.Forms
2.- Insert AnimationView on page
3.- Launch Android Device
### Configuration
Xamarin.Forms 4.5.0.495
Xamarin.Essentials 1.5.2
Com.Airbnb.Xamarin.Forms.Lottie 3.1.0

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x ] :monkey: Xamarin.Forms

[Example project](https://drive.google.com/file/d/1_rmKA5dkZRYuQNQGmJAXWdVKppSSsLdQ/view?usp=sharing)

**Comment by martijn00** [comment]
Update to Android 10
