### ISSUE TITLE
PlaybackStartedCommand not executed on iOS

### ISSUE THREAD

**Issue by dsarbut** [martijn00/LottieXamarin#266]
## 🐛 Bug Report

Starting an animation by setting the IsPlaying property works but the PlaybackStartedCommand is never executed.

### Expected behavior

When the playback starts, the PlaybackStartedCommand is executed.

### Reproduction steps
Use a simple AnimationView in a Xamarin.Forms app running on iOS.
### Configuration

**Version:** 3.1.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [*] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Try 4.0
