### ISSUE TITLE
UWP Build Error

### ISSUE THREAD

**Issue by iWeaverMan** [martijn00/LottieXamarin#268]
## 🐛 Bug Report
1>GENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Повторяющаяся запись.
1>GENERATEPROJECTPRIFILE : error : PRI277: 0xdef00532 - Conflicting values for resource 'Files/Microsoft.UI.Xaml/DensityStyles/Compact.xbf'

Version 3.1.1 use microsoft.ui.xaml 2.3.200213001
Version 3.0.4 use microsoft.ui.xaml 2.3.191211002
Xamarin Forms 4.6 use microsoft.ui.xaml 2.3.191211002

Due to version mismatch, duplication of resources occurs

Requires version microsoft.ui.xaml 2.3.191211002 matching version Xamarin Forms

### Configuration

**Version:** 3.1.1

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fixed in https://github.com/Baseflow/LottieXamarin/commit/5385d89d938e8d2a7ccf33dc6f7d2b227002cb5e
