### ISSUE TITLE
[UWP] PlayFrameSegment and PlayProgressSegment Only Work In Reverse

### ISSUE THREAD

**Issue by MattRames** [martijn00/LottieXamarin#269]
## 🐛 Bug Report

Currently animations will only play in reverse.

### Expected behavior
I would expect a reverse animation and a forward animation segment to work. 

### Reproduction steps
Make the following code change in the sample app and notice how the animation works in reverse and doesn't when going forward.

```
playSegmentsButton.Clicked += (sender, e) =>
{
    animationView.PlayProgressSegment(0.65f, 1.0f); // Doesn't animate
    //animationView.PlayProgressSegment(0.65f, 0.0f); // Animates
};
playFramesButton.Clicked += (sender, e) =>
{
    animationView.PlayFrameSegment(50, 100); // Doesn't animate
    //animationView.PlayFrameSegment(50, 1); // Animates
};
```

### Configuration

**Version:** 3.1.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by MattRames** [comment]
The values passed into the AnimatedVisualPlayer seem correct for progress segements but not frame segments if the comments below are true.

```
/// <summary>Starts playing the loaded animated visual, or does nothing if no animated visual is loaded.</summary>
/// <param name="fromProgress">The point from which to start the animation, as a value from 0 to 1.</param>
/// <param name="toProgress">The point at which to finish the animation, as a value from 0 to 1.</param>
/// <param name="looped">If true, the animation loops continuously between fromProgress and toProgress. If false, the animation plays once then stops.</param>
/// <returns>An async action that is completed when the play is stopped or, if looped is not set, when the play reaches toProgress.</returns>
[MethodImpl]
public extern IAsyncAction IAnimatedVisualPlayer.PlayAsync(
  [In] double fromProgress,
  [In] double toProgress,
  [In] bool looped);
```

Side note, Play(...) is called twice. The action passed into PrepareReverseAnimation, which is Play(...), is invoked and then Play is invoked again.

**Comment by ederjbezerra** [comment]
Same problem here... It works when forwarding first time, and works as expected for reversing any time, but once you reverse it, forward will no longer work anymore.

**Comment by martijn00** [comment]
Try 4.0 or make a PR for that
