### ISSUE TITLE
Binding to iOS

### ISSUE THREAD

**Issue by ryanherman** [martijn00/LottieXamarin#27]
I'm pretty sure I discovered why my iOS project wasn't rendering but my Android was.  

My Animation in the XAML was set as a Binding (See Below).  Once I changed it to the filename vs. setting it after it seems to work.  I had to remove the Xamarin.Forms.iOS nuget and copy and paste the Renderers for the platform.  But now its working.

        
   `<customRenderer:AnimationViewLottie
                    VerticalOptions="StartAndExpand"
                    HorizontalOptions="CenterAndExpand"
                    x:Name="animationView"
                    Animation="{Binding AnimationResource}" BackgroundColor="Transparent"
                    WidthRequest="200" HeightRequest="200" Loop="True" AutoPlay="True"/>`

**Comment by jzeferino** [comment]
Can you paste some information about the error when you used the nuget version?

**Comment by ryanherman** [comment]
No errors come up, it just doesn't animate.  I don't think the Animation property binds correctly on iOS.

**Comment by jzeferino** [comment]
What was the value in `AnimationResource`?

**Comment by ryanherman** [comment]
the JSON file that contained the animation.

**Comment by jzeferino** [comment]
With or without the extension?

**Comment by egimbernat** [comment]
I'm having the same issue, I've tried with and without extension. From XAML and code.
Also with a little delay (Allowing all the screen to full charge), in fact, I don't have lucky.

My final try is initiating Lottie from native iOS project and all was correct.

**Comment by bpater-tp** [comment]
ok, I have finally nailed it - in iOS project of Forms app you need to call:

```            AnimationViewRenderer.Init();```

just before

```            LoadApplication(new App());```

I haven't seen it documented anywhere. Also at least for my example code `HorizontalOptions` and `VerticalOptions` of `AnimationView` element have to be set to `FillAndExpand` or nothing is shown (seems like a bug to me).
