### ISSUE TITLE
Animations not working on iOS when using VS HotRestart feature

### ISSUE THREAD

**Issue by bdaunt99** [martijn00/LottieXamarin#272]
## 🐛 Bug Report

When debugging a Xamarin iOS project using the HotRestart feature of VS (v16.6.2), the animation will not display and will not play. 

### Expected behavior
Animation will display and play as it does in the corresponding Android project. Note that, when building the exact same iOS project via the App Center and then Distributing it to the same iPhone, the animation displays and plays as expected.
 
### Reproduction steps
1. Create a blank Xamarin Forms project
2. Add Com.Airbnb.Xamarin.Forms.Lottie v3.1.2 and Com.Airbnb.iOS.Lottie v2.5.11 nuget packages
3. Add sample "LottieLogo1.json" to the iOS project per the Lottie ReadMe.txt file
4. Add  "AnimationViewRenderer.Init();" line to the AppDelegate.cs file
5. Set "AutoPlay" property of animation to "true"
6 Add a button that, when clicked, calls the animationView.Play();
7. Set the iOS project as the Default Startup Project
8. In the VS Options, enable "HotRestart" under the "Preview Features" section
9. Run the project and respond to the HotRestart setup wizard

[LottieHotStart.zip](https://github.com/Baseflow/LottieXamarin/files/4774511/LottieHotStart.zip)

### Configuration
Requires an Apple Developer account and an iPhone (in this case iPhone 8) connected via USB.

I've attached a minimal sample solution to replicate ("LottieHotStart")

Since it does work properly if the app is built and deployed "normally", I assume this is more of a VS bug than Lottie. I also realize that HotRestart is still in Preview.  But thought I might mention it in case there is some different config or step that I might have missed that would make this work.

**Version:** 1.x

**Platform:** 
- [ X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you try again with 4.0+ ?
