### ISSUE TITLE
Lottie.Forms.UWP.Renderers not defined?

### ISSUE THREAD

**Issue by EmilAlipiev** [martijn00/LottieXamarin#273]
## 🔙 Regression

I dont quite understand why in 3.1.2 i get build error tells me Lottie.Forms.UWP.Renderers not recognized in my xamarin.forms app. I upgraded from 3.0.4 code below was working below in UWP. Did you foget to copy AnimationViewRenderer in your multi targeting?
what was changed?
```
 List<Assembly> assembliesToInclude = new List<Assembly>()
                {                
                    typeof(Lottie.Forms.UWP.Renderers.AnimationViewRenderer).GetTypeInfo().Assembly,
```

### Old (and correct) behavior
3.0.4
 
here are my targets

![image](https://user-images.githubusercontent.com/10422347/85904357-cd30d480-b808-11ea-9b4e-db4a21a505fd.png)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ x] :earth_americas: UWP min 
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms 4.7

**Comment by martijn00** [comment]
You need a higher min version
