### ISSUE TITLE
Support embedded resources

### ISSUE THREAD

**Issue by dansiegel** [martijn00/LottieXamarin#274]
## 🏗 Enhancement Proposal

Lottie is ultimately based on Vector drawings, as such there is no requirement for providing various resolutions for various screen dpi's on each platform as there is with a png. As a result it is just silly to be duplicating these resources on each platform. Support should be added to allow embedding these files in sharable code.

related question: #217

### Pitch

Similar to how FFImageLoading supports a resource URI to load an embedded SVG, the same sort of support should be added to LottieXamarin.

```
resource://AwesomeApp.Resources.lottieFile.json?assembly=[ASSEMBLY FULL NAME]
```

This will cut down on having to duplicate the lottie files across various projects and allow consumers to create libraries that may contain views containing Lottie Animations and then reuse them across various apps.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@dansiegel great idea! Can you make a PR?

**Comment by martijn00** [comment]
Partial support is added in 4.0. I probably need help to add it to iOS.
