### ISSUE TITLE
With the version 3.1.2 (Forms)  is working fine for iOS, not for Android

### ISSUE THREAD

**Issue by albertoiglesias2001** [martijn00/LottieXamarin#276]
### Expected behavior

With this new version, for android is not expected anymore Initialization on android app?

on Mainactivity.cs I use:

using Lottie.Forms.Droid;
 AnimationViewRenderer.Init();

but with the new version we dont have this initialization.

and when I come back to 3.0.4 is working fine

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by robhellest** [comment]
same issue on Android, Xamarin Forms - with same resolution as above ; in my case, using 3.0.0 ;

**Comment by K232** [comment]
For my app, Lottie on Android was not working for weeks / months, even with 3.1.2. Yesterday I've set Android Target Version from API level 28 (Android 9.0) to 29 (10.0) and out of the sudden it's working fine now :-) I'm not sure whether this was the reason for the fix, but I did not do anything on the lottie problem (it was just a lucky coincidence that it's working now) so I just wanted to let you know. Maybe it also helps in your apps?

**Comment by rhellestrae** [comment]
@K232 thanks for feedback; seems to best, and working solution - Lottie version 3.1.2, Android Target version 10.0; best regards;

**Comment by robhellest** [comment]
@K232<https://github.com/K232> thanks for feedback; seems to best, and working solution - Lottie version 3.1.2, Android Target version 10.0; best regards;

305.613.8414
Miami, Florida
RobertHellestrae.com

Sent from my iPad

On Aug 20, 2020, at 3:51 AM, Kai <notifications@github.com> wrote:

﻿

For my app, Lottie on Android was not working for weeks / months, even with 3.1.2. Yesterday I've set Android Target Version from API level 28 (Android 9.0) to 29 (10.0) and out of the sudden it's working fine now :-) I'm not sure whether this was the reason for the fix, but I did not do anything on the lottie problem (it was just a lucky coincidence that it's working now) so I just wanted to let you know. Maybe it also helps in your apps?

**Comment by biapar** [comment]
> For my app, Lottie on Android was not working for weeks / months, even with 3.1.2. Yesterday I've set Android Target Version from API level 28 (Android 9.0) to 29 (10.0) and out of the sudden it's working fine now :-) I'm not sure whether this was the reason for the fix, but I did not do anything on the lottie problem (it was just a lucky coincidence that it's working now) so I just wanted to let you know. Maybe it also helps in your apps?

For lower 28?
