### ISSUE TITLE
Set CacheStrategy to "Strong" from XAML?

### ISSUE THREAD

**Issue by albertoha94** [martijn00/LottieXamarin#278]
Here's the situation, I currently have a view defined inside my `App.xaml` used to show a loading screen when the application is working. This screen contains an `AnimationView` that loads the `loading.json` animation.

```
<StackLayout x:Key="layoutLoading">
            <lottie:AnimationView
                Animation="loading.json"
                IsPlaying="True"
                Loop="true" >
            </lottie:AnimationView>
            <Label
                Margin="{StaticResource StandardSpacing}"
                FontAttributes="Bold"
                FontFamily="{DynamicResource MontserratBoldItalic}"
                FontSize="Subtitle"
                HorizontalTextAlignment="Center"
                Text="{Binding LoadingMessage}">
                <Label.Effects>
                    <effects:ShadowEffect />
                </Label.Effects>
            </Label>
        </StackLayout>
```

When using this layout, the animation is not shown at the start and i assume that is because its loading it.
While checking the documentation I found there's a Caching strategy but I couldn't find a way to use in XAML in the documentation. Is it possible to set the caching strategy in XAML? Thanks.

Here's some additional evidence of my issue:
No icon shows up:
![no_icon](https://user-images.githubusercontent.com/14353851/92316833-164a9500-efbf-11ea-8352-1981c9533634.gif)

Icon shows up:
![icon](https://user-images.githubusercontent.com/14353851/92316839-1e0a3980-efbf-11ea-807e-529e612fc2c2.gif)

**Comment by martijn00** [comment]
Try 4.0
