### ISSUE TITLE
Typo in AnimationView.Duration property causing InvalidCastException

### ISSUE THREAD

**Issue by jBijsterboschNL** [martijn00/LottieXamarin#279]
## 🐛 Bug Report

Found a typo in the Duration property of the AnimationView. This causes an InvalidCastException.

```
public long Duration
{
    get { return (long)GetValue(ProgressProperty); }
    internal set { SetValue(ProgressProperty, value); }
}
```

### Expected behavior

No InvalidCastException being thrown.

### Reproduction steps

1. Clean Xamarin.Forms project
2. Install Lottie NuGet package
3. Add AnimationView
4. Call Duration getter on AnimationView

### Configuration

**Version:** 4.0.0-alpha1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Thanks! Fixed in https://github.com/Baseflow/LottieXamarin/commit/903b469279418db40e4701d986b3dae276c2227b

**Comment by jBijsterboschNL** [comment]
@martijn00, quick action! :) wanted to commit PR later today, but you beat me ;) thanks!
