### ISSUE TITLE
Xamarin.Forms issue

### ISSUE THREAD

**Issue by pavelsedina** [martijn00/LottieXamarin#28]
Hi,
the library seems great, but I have some initial problems :-( I installed NuGet packages into PCL and Droid projects, put sample LottieLogo1.json file inside Asset directory (Droid version), place sample XAML code into PCL:
```
xmlns:forms="clr-namespace:Lottie.Forms;assembly=Lottie.Forms"
...
  <forms:AnimationView 
    x:Name="AnimationView"
    Animation="LottieLogo1.json"
    Loop="True"
    AutoPlay="True"
    VerticalOptions="FillAndExpand"
    HorizontalOptions="FillAndExpand" />
```

But when opening the page, the following error message is shown:

> System.TypeLoadException: Could not load type 'Lottie.Forms.Droid.AnimationViewRenderer' from assembly 'Lottie.Forms.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Any idea how fix that and why is it happening?

thanks!
Pavel

**Comment by martijn00** [comment]
It seems you might not have updated all nugets, not installed it in the native project as well, use the linker which might remove some classes.

**Comment by pavelsedina** [comment]
Hi Martin, thanks for your feedback! I tried to install Com.Airbnb.Android.Lottie, but it gave me the error below. I updated Xamarin.Forms to the latest version, but it didn't update any Xamarin.Android.xxx packages, could this be a problem? Any idea how to solve that? Thanks for any hints!

`Unable to find a version of 'Xamarin.Android.Support.v7.AppCompat' that is compatible with 'Com.Airbnb.Android.Lottie 1.5.2 constraint: Xamarin.Android.Support.v7.AppCompat (>= 25.1.1)', 'Xamarin.Android.Support.Design 23.3.0 constraint: Xamarin.Android.Support.v7.AppCompat (= 23.3.0)', 'Xamarin.Android.Support.v7.MediaRouter 23.3.0 constraint: Xamarin.Android.Support.v7.AppCompat (= 23.3.0)', 'Xamarin.Forms 2.3.4.192-pre2 constraint: Xamarin.Android.Support.v7.AppCompat (= 23.3.0)'.`

**Comment by martijn00** [comment]
Your Android project need to target API lvl 24 or higher. Also you need to update all support packages to 25.1.1.

**Comment by davidlowe** [comment]
Bummer, as far as I can tell, Xamarin.Forms (even the latest pre-release) doesn't support > 23.3 yet.

Nuget reports older versions 1.0.x don't have any dependencies. Would that work Martijn?

**Comment by martijn00** [comment]
As you can see on Nuget: https://www.nuget.org/packages/Xamarin.Forms/2.3.3.193
The limit on v23 has been lifted. Just make sure you are on 2.3.3.193 or higher and target Android v24 or higher and everything will work.

**Comment by allrast** [comment]
Hi @martijn00. I was wondering if i can use your library on versions bellow Androidv24. Can i run this on a device with android 6?

Thanks,
Marco

**Comment by martijn00** [comment]
Yes you can run it on below v24. Your animations just need to be supported. Look at the native project to find out which are.

**Comment by arvindbca123** [comment]
Hi Martijn00 
I want to install your package in xamarin.form, as per your comment need to install seperatlly in android and ios also but in form successfully installed but unable to install in Android, AnimationViewRenderer doesn't exist the the current context when trying to add it to MainActivity.cs
could you help me please..
