### ISSUE TITLE
The AnimationView.Clicked event handler is not working on iOS

### ISSUE THREAD

**Issue by jBijsterboschNL** [martijn00/LottieXamarin#280]
## 🐛 Bug Report

The AnimationView.Clicked event handler is not working on iOS. I've tested this on Android and it works fine on Android.

### Expected behavior

When setting the Clicked event on an AnimationView, the Clicked event should be triggered when the user clicks on the animation.

### Reproduction steps

1. Create new Xamarin.Forms project and install Com.Airbnb.Xamarin.Forms.Lottie NuGet packages to all project
2. Add AnimationView to MainPage
3. Set Clicked event handler
4. Set debug breakpoint inside the on clicked method
5. Run app and click on the specific animation

### Configuration

**Version:** 4.0.0-alpha3

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
It is added here: https://github.com/Baseflow/LottieXamarin/blob/develop/Lottie.Forms/Platforms/Ios/AnimationViewRenderer.cs#L123

Can you see a reason why it is not working?

**Comment by jBijsterboschNL** [comment]
@martijn00, not sure what is causing this. Otherwise I would have given you more details on this issue. Perhaps this Xamarin.Forms issue: https://github.com/xamarin/Xamarin.Forms/issues/10623 ? Anyway, I've managed to work around this issue by adding a Xamarin.Forms.TemplateView with a TapGestureRecognizer on top of the AnimationView. Not very proud of this work around, but for now I can continue with this. But maybe we should keep this issue open to find the exact problem and fix this!

**Comment by martijn00** [comment]
I've fixed it. Can you test the new release that will be out soon?

**Comment by jBijsterboschNL** [comment]
@martijn00 , I don't see a new release so I can test this, is that correct? Or is there a nightly NuGet package available that I can use??

**Comment by jBijsterboschNL** [comment]
@martijn00, I've tested this bug fix with the new released version v4.0.0-alpha4 and can confirm that it works now :) thanks for your quick response and fix on this! Cheers
