### ISSUE TITLE
Breaking Changes in v4.0?

### ISSUE THREAD

**Issue by darrabam** [martijn00/LottieXamarin#282]
Hi, 

There seems to be many breaking changes in v4.0. I spent sometime fixing my code in both xaml and cs till finally compiles, but then the animation doesn't play when calling PlayAnimation(). 

Is there a documentation explaining the changes in the latest release so that I can migrate smoothly without spending hours trying different things?

Thanks,

**Comment by louisoftokyo** [comment]
Exactly the same problem here - I can't find any documentation for the new release or its breaking changes. What happened to the Loop, PlaybackStartedCommand and PlaybackFinishedCommand properties? @martijn00

**Comment by martijn00** [comment]
Maybe you can open a PR to add the documentation? Let's start with opening a proper issue with all the template filled in on your side.

**Comment by darrabam** [comment]
> Maybe you can open a PR to add the documentation? Let's start with opening a proper issue with all the template filled in on your side.

I’m sorry, but why would I need to open a PR? I don’t have any documentation to push!

**Comment by martijn00** [comment]
It would be good to give back to the community, or maybe you can pay me to make the documentation ;)

**Comment by biapar** [comment]
Sorry, but I think that if there are some breaking changes you need to advise the community.
