### ISSUE TITLE
Might have a solution for the Linker

### ISSUE THREAD

**Issue by taz4270** [martijn00/LottieXamarin#283]
https://github.com/Baseflow/LottieXamarin/blob/b1e1988d243552b74b48b620daa3103643e00f3d/Lottie.Forms/Platforms/Ios/AnimationViewRenderer.cs#L25

Have you tried to do this https://montemagno.com/optimizing-xamarin-apps-libraries-with-the-linker/#preserveeverything ?
This might help you a lot and save the users from using unecessary space for a dummy!

**Comment by martijn00** [comment]
Can you open a PR for this?

**Comment by taz4270** [comment]
Im not able, i dont know why 
![image](https://user-images.githubusercontent.com/44700489/94479708-19573080-01cd-11eb-9716-4145d825fd35.png)
But i forked it right and made the changes right https://github.com/taz4270/LottieXamarin, make sure to test it out because i dont have all libraries

**Comment by taz4270** [comment]
I found the issue, but let me get home later and then i will PR
