### ISSUE TITLE
Azure Unit Test Project Build Fails on Mac

### ISSUE THREAD

**Issue by mauro-dasilva** [martijn00/LottieXamarin#284]
## 🐛 Bug Report

On Azure DevOps, when using the hosted MacOS agent, the build now fails when building our Xamarin Unit Test project after upgrading to the V4.0 of LottieXamarin. The error that is shown is as follows:
  `/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WPF' was not recognized 
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized`

If I revert to the previous major release, it builds fine.

### Expected behavior
The unit test project should complete successfully

### Reproduction steps
I'm not sure if building the solution on a Mac would surface the same issue, but basically build a solution with a Unit Test project in Azure DevOps with the version 4.0 of Lottie Xamarin.

### Configuration

**Version:** 4.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
See https://github.com/Baseflow/LottieXamarin/issues/294#issuecomment-719932259
