### ISSUE TITLE
OnFinishedAnimation is never raised

### ISSUE THREAD

**Issue by RadoslawKubas** [martijn00/LottieXamarin#285]
## 🐛 Bug Report
I want to call method after the animation plays once, but it seems OnFinishedAnimation is never called. My animation view definition is:

```
<forms:AnimationView  x:Name="AnimationView"
 RepeatMode="Restart" 
 RepeatCount="1"
 AutoPlay="False"
                                     
 OnStopAnimation="AnimationView_OnOnStopAnimation"
 OnPauseAnimation="AnimationView_OnOnPauseAnimation"
 OnRepeatAnimation="AnimationView_OnOnRepeatAnimation"
 OnFinishedAnimation="AnimationView_OnOnFinishedAnimation"
/>
```

Than to play animation I use:
```
private void PlayAnimation(string animation)
        {
            AnimationView.Animation = animation;

            AnimationView.PlayAnimation();
        }
```

The result is unexpected, first time I call PalyAnimation it seems to be infinitive (loop forever, with restarting), 2nd time I call same PlayAnimation (or with different animation file) it play just once, but OnFinishedAnimation is never raised.

### Expected behavior

Animation play 1 time and when its finish OnFinishedAnimation is raised. 

### Reproduction steps

1. Create animation view as in the example.
2. Play animation.
3. Check if event was raised.

### Configuration

**Version:** 4.0.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you try again with 4.0.3?

**Comment by RadoslawKubas** [comment]
I tested just now, it seems to be fine now :) Thank you!

**Comment by muenchris** [comment]
Sorry to re-open this. But the event is not firing on UWP. It fires fine on Android and IOS but not UWP.

**Comment by muenchris** [comment]
Here is a fix for this: 
in "Lottie.Forms" 
Platforms/Uap/AnimationViewRenderer.cs line 55:

                        _animationView.PlayAsync(0, 1, Element.RepeatMode == RepeatMode.Infinite).AsTask().GetAwaiter().OnCompleted(() => 
                        {
                            e.NewElement.InvokeFinishedAnimation();
                        });
