### ISSUE TITLE
Repeat Mode Infinite only plays once on Android

### ISSUE THREAD

**Issue by mauro-dasilva** [martijn00/LottieXamarin#287]
## 🐛 Bug Report
In V4.0.3 it seems that on the Android side of Xamarin Forms, whenever you set the `RepeatMode` to `Infinite` it only plays the animation once. However, on iOS side this seems to work. I think the iOS repeat works due to the recent commit made here - https://github.com/Baseflow/LottieXamarin/commit/b9fe62da98b5aa7b9db695ab8f64905ceae50940 

It seems to fix up the iOS/Mac side of things, but not for Android.

### Expected behavior
When the RepeatMode is set to Infinite the animation keeps on playing indefinately

### Reproduction steps
* Create an animation
* Set the Repeat Mode to Infinite

### Configuration

**Version:** 4.0.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Fix is in 4.0.4
