### ISSUE TITLE
Infinite Mode Reversing Animation on Android

### ISSUE THREAD

**Issue by mauro-dasilva** [martijn00/LottieXamarin#288]
## 🐛 Bug Report

Recently, the repeat mode on Android was corrected so that the animation now repeats once it has completed. However, it seems that when the animation reaches the end, it reverses itself and plays the animation backwards. 

In the previous version (3.x) if the `Loop` property was set to `True` it would repeat the animation indefinitely, as `Infinite` now does, however the animation repeated itself from the start and didn't reverse itself.

This leads to some funny looking animations, as per the one below

![untitled](https://user-images.githubusercontent.com/37144094/95083027-81b68c80-074e-11eb-9512-f9a8999b7f7d.gif)

On iOS, the `Infinite` mode restarts itself from the beginning, as expected.

### Expected behavior
When the `Inifinite` animation reaches the end, it should start again from the beginning and not reverse itself.

### Reproduction steps
* Create an animation
* Set its `RepeatMode` to `Infinite`

### Configuration

**Version:** 4.0.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
That is weird. What if you set `RepeatMode` to `Reverse`? What you see is what I would expect in the `Reverse` mode.

**Comment by mauro-dasilva** [comment]
Just tested `Reverse` mode and it starts the animation from the beginning and doesn't reverse it as expected.

**Comment by martijn00** [comment]
Hmm interesting. I currently use ` _animationView.RepeatMode = (int)e.NewElement.RepeatMode;` but maybe that doesn't convert correctly to the native system. See https://github.com/Baseflow/LottieXamarin/blob/develop/Lottie.Forms/Platforms/Android/AnimationViewRenderer.cs#L117

Can you look into how this should work and give me some hints?

**Comment by xamiell** [comment]
Having the same issue on Android. iOS works fine.

Xamarin.Forms 4.8.1364
Com.Airbnb.Xamarin.Forms.Lottie 4.0.4

**Comment by martinapapaliska** [comment]
I just made a PR that fixes this issue. It would be great to get a release as soon as possible. Link to the PR [here](https://github.com/Baseflow/LottieXamarin/pull/293)

**Comment by martijn00** [comment]
4.0.6 is online on nuget
