### ISSUE TITLE
Can't run sample on iOS device

### ISSUE THREAD

**Issue by Berfhaen** [martijn00/LottieXamarin#29]
Hi there!

This project looks wonderful. I managed to run it on a simulator but the app crashes on my device (iPhone 7 iOS 10.2). I have the following exception :

> System.ExecutionEngineException: Attempting to JIT compile method 'Airbnb.Lottie.LAAnimationView:.ctor (Foundation.NSUrl)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.

The exception happens here:

```
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var lottieView = new LAAnimationView(NSUrl.FromString("https://raw.githubusercontent.com/airbnb/lottie-ios/master/Example/Assets/LottieLogo1.json")); // <--- Exception here
            [...]
        }
```

**Comment by EDaniel38** [comment]
I tried the latest version as of today and I still get the error. How can we help?
![microsoft visual studio](https://cloud.githubusercontent.com/assets/26481302/24298191/89f92d24-10a5-11e7-80bd-0e5ce5c7a719.jpg)

**Comment by Berfhaen** [comment]
I tried the latest version as of today and I still get the same error. How can we help?
![microsoft visual studio](https://cloud.githubusercontent.com/assets/8374249/24298300/db5c4372-10a5-11e7-9e7c-1419450e891f.jpg)

**Comment by martijn00** [comment]
I can run the samples perfectly fine, do you have more information? What is different in you project?

**Comment by Berfhaen** [comment]
I've just cloned the project, changed the project identifier and run.

**Comment by martijn00** [comment]
@fabionuno Any idea about this?

**Comment by Berfhaen** [comment]
I don't have a clue. When I debug, it happens in the constructor of `LOTAnimationView`. As I don't have access to the inner code, I don't know.

**Comment by fabionuno** [comment]
I'll try to investigate this.
I'm not able to reproduce this using Xamarin Studio on a Mac and running in a iPhone5 with iOS 10.2.1
@martijn00 can you test using Visual Studio as the @Berfhaen ?

**Comment by tomglanville** [comment]
I had a similar issue - it appears the problem was caused by running the app in debug mode. I switched to release and it worked on the simulator and physical device.

@fabionuno Do you have any issues when running in debug mode?

**Comment by EthanHitGub** [comment]
I am running Xamarin.Forms and have an issue on iOS (11.0) with simulators. My animation runs fine in my Android project but doesn't start on iOS. I am running in debug.

Were or are there any issues running animations in debug on iOS?
