### ISSUE TITLE
AnimationViewRenderer.Init() disappeared after upgrading to 4.0.4

### ISSUE THREAD

**Issue by motoko89** [martijn00/LottieXamarin#291]
Not sure if it's a bug but after upgrading to 4.0.4 the method doesn't exist anymore. Do we still need to call it on each platform?

This is Xamarin.Forms

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
It's not necessary anymore. See https://github.com/Baseflow/LottieXamarin/pull/286
