### ISSUE TITLE
Create a Source property on AnimationView that loads the json from embedded resources

### ISSUE THREAD

**Issue by softlion** [martijn00/LottieXamarin#295]
## 🚀 Feature Requests

Xamarin is about not duplicating code and files.

Instead of copying the json file to the native resources of ios/android, it would be nice to have them load from a stream, from .net embedded resources.

### Platforms affected (mark all that apply)
- [X] :iphone: iOS
- [X] :robot: Android
- [X] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [x] :apple: MacOS
- [X] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is already possible on Forms. Can you make some extension methods and a PR if you want it different?

**Comment by softlion** [comment]
There is nothing about that in the doc? How it works ?

**Comment by softlion** [comment]
In fact there is no AnimationSource property in Lottie.

**Comment by softlion** [comment]
XF.Material is not referencing the latest lottie nuget ...

**Comment by martijn00** [comment]
Sure? I thought i updated it recently.
