### ISSUE TITLE
crash on uwp

### ISSUE THREAD

**Issue by softlion** [martijn00/LottieXamarin#296]
## 🐛 Bug Report

I suppose it is not supported on UWP. So why is there a renderer and why it crashes ?

### Expected behavior

Don't crash. Ignore lottie tags.

### Reproduction steps

Any animation

### Configuration

**Version:** 4.x, 3.x, ...

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
It was working last time i tested something, but i don't use UWP very often. It should be possible to get this working. Can you debug and make a PR?

**Comment by EmilAlipiev** [comment]
For me last working version was 3.1.2 on UWP but this version is also not working now. I believe after updating XF 4.8 it also got broken. Can you try 3.1.2 to see if it works for you?

**Comment by EmilAlipiev** [comment]
just tested again and it seems like latest XF versions are not working with any of the versions on UWP. last working version for me was xf 4.6 and lottie 3.1.2 version.
I tried to debug the problem but project is not in buildable state. a lot of errors on both master and develop branches

**Comment by martijn00** [comment]
I just compiled the project and made a new release, so it is in buildable state. You probably need to update your visual studio.
