### ISSUE TITLE
Lottie 4.0.7 doesn't work on Xamarin.Forms Android project

### ISSUE THREAD

**Issue by jmarti326** [martijn00/LottieXamarin#302]
## 💬 Questions and Help

Hi, I was able to made it work on iOS, but in Android I am unable to view the animation.  After some Google search some recommend to install the Com.Airbnb.Android.Lottie along side Com.Airbnb.Xamarin.Forms.Lottie but this just makes the app crash once is install in the emulator.

I would like to know if there is a special step I need to do for the new version 4.0.7.

**Comment by martijn00** [comment]
Target Android 10 and use the latest visual studio.

**Comment by jmarti326** [comment]
Hi @martijn00 thank you for taking the time to comment on my open item.
I do have the following configuration, if there is anything I need to change or fix other than that, please let me know. Again, thank you for the time.

Error I am getting when deploying and opening the app in the Android Simulator.
![Screen Shot 2020-11-23 at 2 42 35 PM](https://user-images.githubusercontent.com/4348632/100002906-a799fe00-2d9b-11eb-81e2-71423c78e246.png)

Nuget Install in the Android Project
![Screen Shot 2020-11-23 at 2 47 29 PM](https://user-images.githubusercontent.com/4348632/100002915-ac5eb200-2d9b-11eb-8f01-0ce8b9f476f3.png)

MainPage.xaml
![Screen Shot 2020-11-23 at 2 48 08 PM](https://user-images.githubusercontent.com/4348632/100002923-b1236600-2d9b-11eb-83b5-99429adf365e.png)

Android Target Framework
![Screen Shot 2020-11-23 at 2 50 12 PM](https://user-images.githubusercontent.com/4348632/100002941-b5e81a00-2d9b-11eb-8dc0-9b85df4b4534.png)

**Comment by martijn00** [comment]
You need to use AndroidX instead of Android Support v7.

**Comment by jmarti326** [comment]
We might be getting closer. 😅🙈

I looked for this error online, and tried a couple of recommendations.  Still continue to have the error. 

![Screen Shot 2020-11-23 at 5 14 05 PM](https://user-images.githubusercontent.com/4348632/100016098-4da33380-2daf-11eb-86d1-322b14c0d741.png)

![Screen Shot 2020-11-23 at 5 12 26 PM](https://user-images.githubusercontent.com/4348632/100016123-53007e00-2daf-11eb-80f4-b8ec2a14de41.png)

**Comment by jmarti326** [comment]
After a little bit of more google search, and a comment from a team member, I was able to get the library working in Android.

Need to go to Toolbar.xml inside the layout folder.

Change
android.support.v7.widget.Toolbar

To
androidx.appcompat.widget.Toolbar

![image](https://user-images.githubusercontent.com/4348632/100019214-09fef880-2db4-11eb-8306-55dacfe97476.png)


Result

![image](https://user-images.githubusercontent.com/4348632/100019264-1f742280-2db4-11eb-84bf-5774af80218b.png)

**Comment by jmarti326** [comment]
@martijn00 Thank you for your help. :)
