### ISSUE TITLE
Not working in Android

### ISSUE THREAD

**Issue by Sumit2668** [martijn00/LottieXamarin#307]
## 🐛 Bug Report

I have using Lottie Plugin 4.0.8 and add the JSON file from the [(https://lottiefiles.com/)], after that I trying to check in both, iOS working fine but android is not working means not showing anything in android,
what should I do?

 My results Like this below screens.
<img width="200" alt="iOS" src="https://user-images.githubusercontent.com/26775231/102499535-5088ff80-40a1-11eb-93bd-2cf725c03e46.png">

<img width="200" alt="Android" src="https://user-images.githubusercontent.com/26775231/102499628-6dbdce00-40a1-11eb-889b-0d4976f25eb4.jpg">

**Comment by martijn00** [comment]
Please debug and come up with a PR
