### ISSUE TITLE
StopAnimation does not reset the animation on Android

### ISSUE THREAD

**Issue by joshardt** [martijn00/LottieXamarin#308]
## 🐛 Bug Report
The StopAnimation method does not reset the animation on Android. On iOS there are no problems. The interface documentation of StopAnimation is set to the following: "Will stop and **reset** the currently playing animation".

As a workaround I've tried to use `animationView.PlayMinAndMaxProgress(0.0f, 0.0f);` but this results in further problems because when I then restart the animation, the animation instantly finishes. Even when I set `animationView.MaxProgress = float.MaxValue;` I see no difference.

### Expected behavior
The Animation gets reseted on Android when I use the StopAnimation method.

### Reproduction steps
```csharp
var animationView = new AnimationView();
animationView.Animation = "animation.json";

animationView.PlayAnimation();

animationView.OnFinishedAnimation += (sender, args) =>
{
    animationView.StopAnimation();
};
```

### Configuration

**Version:** 4.0.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you make a PR?

**Comment by joshardt** [comment]
Yes, I can do it. But not sure when exactly. Christmas first 🎅

**Comment by joshardt** [comment]
@martijn00 please have a look on my PR.
