### ISSUE TITLE
Error inflating class android.support.v7.widget.Toolbar

### ISSUE THREAD

**Issue by z646587572** [martijn00/LottieXamarin#31]
Error:    Android.Views.InflateException: Binary XML file line #1: Error inflating class android.support.v7.widget.Toolbar.

I Find a Solution:

The created app used xamarin.forms version 2.3.3.180.
After changing this to xamarin.forms version 2.3.3.175, the error was gone.

PS: THis is a Tips

**Comment by martijn00** [comment]
I've published a new release for Forms. Please try that.
