### ISSUE TITLE
Repeatmode Infinite Compilation error

### ISSUE THREAD

**Issue by sjorsmiltenburg** [martijn00/LottieXamarin#310]
https://github.com/Baseflow/LottieXamarin/issues/305 
mentions the use of RepeatCount="Infinite" 

But when I use this value I get the following compilation error 
"Invalid value for property 'RepeatCount': 'Infinite'

Is this a supported value? and if so how do I make my error dissapear?

**Comment by martijn00** [comment]
Please fill out a proper issue template with more detail

**Comment by sjorsmiltenburg** [comment]
my bad, i read repeatCOUNT= infinite, it was repeatMODE = infinite

**Comment by sjorsmiltenburg** [comment]
i guess it had to do with the comment in the enum RepeatMode.cs which is suggestive this is possible

/// When the animation reaches the end and RepeatCount is Infinite or a positive value, the animation reverses direction on every iteration.
