### ISSUE TITLE
Setting Scale results in null error

### ISSUE THREAD

**Issue by sjorsmiltenburg** [martijn00/LottieXamarin#311]
## 🐛 Bug Report

Given the following animation

<forms:AnimationView Grid.Row="1" Grid.Column="1" Animation="loading3.json" x:Name="LoadingCircle"
                                     AutoPlay="True"
                                     RepeatMode="Restart"
                                     RepeatCount="9999" 
                                     Scale="1.85"
                                     HorizontalOptions="FillAndExpand"
                                     VerticalOptions="FillAndExpand" 
                                     IsVisible="{OnPlatform UWP=false, iOS=true,Android=true}" />

I receive the following error during runtime

System.ArgumentNullException: 'Value cannot be null.
Parameter name: property

When i remove the Scale property it loads correctly.

I also tried to set it from code behind
LoadingCircle.Scale = 1.85f; but this result in a similar error.

However, when I am running on Xamarin.Forms - Android with Hot Reload and I insert the scale property after the app has launched it works, (the animation is reloaded and scaled.

### Expected behavior
should work

### Configuration

**Version:** 4.04

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Did you try update to 4.0.8?
