### ISSUE TITLE
Not showing anything in release mode. Not reporting any error ?

### ISSUE THREAD

**Issue by Cfun1** [martijn00/LottieXamarin#314]
## 🐛 Bug Report

- I would love to see a decent official documentation, showing in a simplified  bullet list step by step the things a user needs to do for a startup not more (which package to install? in which project? where to save json?). Also a troubleshooting FAQ would be very helpful. I am sorry to say but I found the current docs (readme) is kind of messy, confusing and lacking details (maybe it only me).

- Lot of questions hanging in StackOverflow about Lottie not working without any clear reason (sometimes the reason is silly but hard to find), a better handling and reflecting errors to users will be a big plus, the same as a working up-to-date sample.

- My issue is that Lottie is working perfectly in debug mode but not in release. 
cc @martijn00

**Comment by Cfun1** [comment]
@martijn00 is this package still maintened ?

**Comment by martijn00** [comment]
Please open a PR if you want to add or fix something.

**Comment by Cfun1** [comment]
No problem, sorry to bother you, I though this repo had a higher activity.

since this issue is closed, do you recommend opening a new issue related only to the issue that the animation is not shown in release mode?

**Comment by martijn00** [comment]
Since this is working for all other people i think this is something on your side. Otherwise i recommend making a PR
