### ISSUE TITLE
Com.Airbnb.Xamarin.Forms.Lottie 4.09

### ISSUE THREAD

**Issue by burakglc** [martijn00/LottieXamarin#324]
<forms:AnimationView
            x:Name="animationView"
            Animation="42201-star.json"   
            AutoPlay="True"
            WidthRequest="300"
            HeightRequest="300" 
            RepeatMode="Restart"
            VerticalOptions="Center"
            HorizontalOptions="Center" />

not showing Json file in phone

**Comment by artifacts-dav** [comment]
Hi, if you mean that it doesn't play the animation.
I solved it using this values
`AnimationSource="EmbeddedResource"
Animation="resource://animation.json?assembly=MyApp"`
And moving the file to XF shared project with Build Action as **Embedded resource**

It works on Android, idk if it will in iOS 

In my case was the only way to get it play.
