### ISSUE TITLE
Forking Issues

### ISSUE THREAD

**Issue by taz4270** [martijn00/LottieXamarin#343]
## 🐛 Bug Report
Just fork, it will appear like this 
![image](https://user-images.githubusercontent.com/44700489/122732318-1547d300-d274-11eb-9ce7-595fd79c756b.png)

**Version:** 4.10

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by muenchris** [comment]
I posted the same as #332. 
It still compiles with older version of VS 2019 (16.9)
