### ISSUE TITLE
Animation Disappear after navigation in runtime.

### ISSUE THREAD

**Issue by ElecTwix** [martijn00/LottieXamarin#372]
## 🐛 Bug Report
Lottie Animation will disperse after changing the runtime navigation page.

### Expected behavior

Just don't disappear for no reason.

### Reproduction steps

1. Create 2 Pages
2. Set Navitagion in App.xaml.cs
3. Change Navigation page in Runtime
4. And Animation is gone.

### Configuration

**Version:** 4.1.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by kashifkhankk** [comment]
Animation disappearing on sorting the ObservableCollection in xamarin iOS project.
