### ISSUE TITLE
support netstandard2.1

### ISSUE THREAD

**Issue by AaronBastian** [martijn00/LottieXamarin#374]
## 🏗 Enhancement Proposal

Add support for netstandard2.1

### Pitch

As projects migrate 1 step forward from netstandard2.0 to netstandard2.1, any application using this Lottie package cannot upgrade.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
There is no benefit in this. The next step will be to move to .net6.0.
