### ISSUE TITLE
[Android] Since update with version 4.1.0 some Lottie no longer display

### ISSUE THREAD

**Issue by Seuleuzeuh** [martijn00/LottieXamarin#376]
## 🔙 Regression

On a Xamarin forms project, targeting Android, i've update my project with the last package 4.1.0 and an animation no longer display : [Lottie file](https://lottiefiles.com/10000-empty-box)

### Old (and correct) behavior
Animation displaying (with version 3.0.4)

### Current behavior
No animation visible, screen is empty (with version 4.1.0)

### Reproduction steps
Use this [lottie file](https://lottiefiles.com/10000-empty-box) , and try it in version 4.1.0 on Android.

### Configuration

**Version Com.Airbnb.Xamarin.Forms.Lottie :** 4.1.0
**XF :** 5.0.0.2337 

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
You probably need to target a higher Android version.
