### ISSUE TITLE
Plans for Forms.UWP support?

### ISSUE THREAD

**Issue by paulanthonymorris** [martijn00/LottieXamarin#39]
My team is excited about this project. Are there plans to support Forms.UWP? Has any work been done toward that goal?

**Comment by martijn00** [comment]
Lottie for Xamarin depends on the Native Lottie libraries. Since they don't support UWP this will not be possible for now. Whenever they add support we will add it to Xamarin as well.

**Comment by JimSEOW** [comment]
https://github.com/martijn00/LottieXamarin/pull/63
