### ISSUE TITLE
Not able to make running animations

### ISSUE THREAD

**Issue by PaulHoets** [martijn00/LottieXamarin#43]
I am having difficulty getting this and several other AE exports working.
Extra compositions also don't display, and it is quite a headache, even if they are being delayered very carefully.

This one was made very carefully and simply, yet it doesn't do it.

Any ideas?

[FallingBallTest.zip](https://github.com/martijn00/LottieXamarin/files/824741/FallingBallTest.zip)

**Comment by fabionuno** [comment]
Hi @PaulHoets not all AE features are supported by Lottie yet. 
You can check the supported features by [Android](https://github.com/airbnb/lottie-android#supported-after-effects-features)  and [iOS](https://github.com/airbnb/lottie-ios#supported-after-effects-features) 

I saw that your animation has an unsupported shape by Lottie:
`[LOTShapeGroup shapeItemWithJSON:frameRate:compBounds:]: Unsupported shape:rd name:Round Corners 1`

**Comment by PaulHoets** [comment]
Thanks for the reply.

Can text be included in an exported animation?

**Comment by fabionuno** [comment]
Unfortunately Lottie doesn't support text (yet). You can track its progress in [Add support for text #173](https://github.com/airbnb/lottie-android/issues/173)

**Comment by FernandoPiche** [comment]
Hi, I have the same problem, My animation doesn´t run in my proyect but if I try another animation runs normally. Any ideas?

[Icono-Gira.zip](https://github.com/martijn00/LottieXamarin/files/952350/Icono-Gira.zip)
