### ISSUE TITLE
Android compilation error

### ISSUE THREAD

**Issue by RobGibbens** [martijn00/LottieXamarin#46]
- Create a new Android project
- Add the latest stable Xamarin.Forms (2.3.3.193 now)
    - The Android support libraries are all 23.3.0
- Add the latest Lottie forms nuget package (1.5.2.0 now)
    - Support packages get updated to 25.1.1
- Build

Getting 
```
java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
```

**Comment by martijn00** [comment]
I suspect this to be because of the android support library update. Did you try cleaning the obj and bin folders?

I'll try and reproduce this as soon as possible.

**Comment by RobGibbens** [comment]
@martijn00 Yes, I've tried it on multiple projects, on four different machines (Mac and Windows, VSWin, VSMac, and XamStudio)

**Comment by martijn00** [comment]
Ok, I'll try to look into this sometime soon.

**Comment by martijn00** [comment]
The package `Xamarin.Android.Support.v4` is not updated when you add Lottie initially. This is because starting from Android Support v24.2 Support.v4 doesn't exists anymore. If you update this one manually it works.
