### ISSUE TITLE
How to add Folder image in Xamarin Forms (PCL)

### ISSUE THREAD

**Issue by golo98** [martijn00/LottieXamarin#48]
Hi, in a Xamarin Forms App (PCL), how to add the images folder in android and ios projects to lottie animation?

Thanks in advanced.

**Comment by paradisehuman** [comment]
Hi. I have same problem. Please Help.

**Comment by golo98** [comment]
Hi @paradisehuman, I solved temporarily as follows:

* Install the Lottie platform nugget package on Android and iOS projects.
* In the PCL project, from this repository (Lottie.Forms) copy the file AnimationView.cs and aggregate this code:
```
public static readonly BindableProperty IsFolderImagesAddedProperty = BindableProperty.Create(nameof(IsFolderImagesAdded),
            typeof(bool), typeof(AnimationView), default(bool));

public bool IsFolderImagesAdded
        {
            get { return (bool)GetValue(IsFolderImagesAddedProperty); }

            set { SetValue(IsFolderImagesAddedProperty, value); }
        }
```

* In Android and iOS projects add the correspondants files AnimationViewRenderer.cs, from Lotttie.Forms.Droid and Lottie.Forms.iOS.
* On Android add this code to the AnimationViewRenderer.cs file
OnElementChanged method
```
            if (e.NewElement != null)
            {
                e.NewElement.OnPlay += OnPlay;
                e.NewElement.OnPause += OnPause;
                _animationView.Loop(e.NewElement.Loop);
                if (!string.IsNullOrEmpty(e.NewElement.Animation))
                {
                    _animationView.SetAnimation(e.NewElement.Animation);
                    Element.Duration = TimeSpan.FromMilliseconds(_animationView.Duration);
                }
                if (e.NewElement.IsFolderImagesAdded)
                {
                    _animationView.SetImageAssetsFolder("images");
                }
                if (e.NewElement.AutoPlay)
                {
                    _animationView.PlayAnimation();
                }
            }
```
OnElementPropertyChanged method
```
            if (e.PropertyName == AnimationView.AnimationProperty.PropertyName)
            {
                _animationView.SetAnimation(Element.Animation);
                Element.Duration = TimeSpan.FromMilliseconds(_animationView.Duration);
                if (Element.IsFolderImagesAdded)
                {
                    _animationView.SetImageAssetsFolder("images");
                }
                if (Element.AutoPlay)
                {
                    _animationView.PlayAnimation();
                }
            }

```

* On iOS, I only add the images directly on the root of the project and is working.
* On the XAML file
`<forms:AnimationView x:Name="AnimationView" Animation="animation.json" Loop="True" AutoPlay="True" IsFolderImagesAdded="True" VerticalOptions="Center" HorizontalOptions="Start" HeightRequest="150" WidthRequest="150"/>
`

I hope this can help you.

**Comment by paradisehuman** [comment]
@golo98 Thank you for your help. But unfortunately a gray circle is showed me instead of the images. Where must be image folder in Android project ? In the root ? and what is the Images build action?

**Comment by golo98** [comment]
@paradisehuman, on android project, the lottie animation file and the images subfolder resides in the Assets folder, on the iOS project the lottie animation and the respectives images I put in the root project folder.

**Comment by paradisehuman** [comment]
@golo98 I put Image in Assets folder and image build action is AndroidAssets and nothing has changed !

**Comment by golo98** [comment]
@paradisehuman 

![image](https://cloud.githubusercontent.com/assets/13257795/25317367/4355eb5c-282c-11e7-91e2-f6660cf078ef.png)

myanimation.json, is the lottie animation and the "images" subfolder in Assets contains the respectives images.
```
<forms:AnimationView 
    x:Name="AnimationView"
    Animation="myanimation.json"
    Loop="True"
    AutoPlay="True"
    IsFolderImagesAdded="True"
    VerticalOptions="Center"
    HorizontalOptions="Center" 
    HeightRequest="300" WidthRequest="300"/>
```

On iOS
![image](https://cloud.githubusercontent.com/assets/13257795/25317424/3aed83d4-282d-11e7-8214-ab44ea08643e.png)

**Comment by paradisehuman** [comment]
@golo98 My problem was solved. my after effect project had problem. I replace another project and it works like a charm. Thank you .

**Comment by encrypt0r** [comment]
@golo98 is there any reason why we can't have an "Images" folder property on the animation view itself?

**Comment by encrypt0r** [comment]
@martijn00 is there any reason why we can't have an "ImagesFolderPath" property on the animation view itself?
