### ISSUE TITLE
Debugging Lottie

### ISSUE THREAD

**Issue by rizaanlakayCW** [martijn00/LottieXamarin#52]
Hi, I'm trying to get an animation to work using Lottie for Xamarin Forms. I've put the json in the Assets folder as an Android Asset. It runs with no errors, but the animation does not show.

Is there a way to debug the problem or can anyone give any ideas?

Downloaded the Lottie for Xamarin Forms 1.5.2 using Xamarin.Forms v2.3.4.224
 
I’m using the LottieLogo1.json in my Android Assets folder and marked the file as an AndroidAsset.
 
The Android project is set to compile using Android v 7.1
Target Android version set to 7.1
 
The project builds and runs but nothing loads on the screen.
 
 
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MediSprint" xmlns:forms="clr-namespace:Lottie.Forms;assembly=Lottie.Forms"
             x:Class="MediSprint.MainPage">
    <StackLayout>
        <forms:AnimationView 
                x:Name="AnimationView"
                Animation="LottieLogo1.json"
                Loop="True"
                AutoPlay="True"
                VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand" />
    </StackLayout>
</ContentPage>

**Comment by martijn00** [comment]
Look at the samples in this repo to see how it works.
