### ISSUE TITLE
Animations doesn´t run

### ISSUE THREAD

**Issue by FernandoPiche** [martijn00/LottieXamarin#56]
Hi, I am trying to run my animation in xamarin forms but doesn´t work, put If I change the animation for one of the page provides like LottieLogo1.json works normally. I am using the same code I only change the name of de file. Some can help me.

[Icono-Gira.zip](https://github.com/martijn00/LottieXamarin/files/952519/Icono-Gira.zip)

**Comment by golo98** [comment]
Hi @FernandoPiche , if you animation have images review this post [https://github.com/martijn00/LottieXamarin/issues/48](url)

**Comment by FernandoPiche** [comment]
Thanks, but I can´t see your link.

**Comment by golo98** [comment]
@FernandoPiche, I corrected the link.
