### ISSUE TITLE
iOS Simulator

### ISSUE THREAD

**Issue by calibrae** [martijn00/LottieXamarin#57]
Is Lottie supposed to work in the ios simulator? 
I have a XAML parse exception on the page containing the animation.
I've linked nuggets com.airbnb.xamarin.forms.lottie on both my pcl and ios projects
and com.airbnb.ios.lottie on ios project.

Thanks for you help and this great lib

**Comment by martijn00** [comment]
Yes it work in the simulator. Look at the samples to see how.
