### ISSUE TITLE
Problem when adding Com.Airbnb.Xamarin.Forms.Lottie in iOS project

### ISSUE THREAD

**Issue by homerokzam** [martijn00/LottieXamarin#59]
In a Xamarin.Forms project when I add the lib Com.Airbnb.Xamarin.Forms.Lottie, in iOS project, the following problem occurs:

/Users/homerokzam/Projects/Lottie/iOS/MTOUCH: Error MT0023: The root assembly /Users/homerokzam/Projects/Lottie/iOS/bin/iPhoneSimulator/Debug/Lottie.iOS.exe conflicts with another assembly (/Users/homerokzam/Projects/Lottie/packages/Com.Airbnb.iOS.Lottie.1.5.1.1/lib/xamarinios/Lottie.iOS.dll). (MT0023) (Lottie.iOS)

**Comment by bpater-tp** [comment]
change the name of your iOS assembly in project settings. i had the same problem

**Comment by homerokzam** [comment]
It worked!

Thanks.
