### ISSUE TITLE
how we will create animations?

### ISSUE THREAD

**Issue by halukmy** [martijn00/LottieXamarin#6]
is there how to for xam.android?

**Comment by fabionuno** [comment]
Animations are created with Adobe After Effects and exported as JSON files with [Bodymovin](https://github.com/bodymovin/bodymovin) plugin.
You can check this repo https://github.com/fabionuno/LottieXamarin-Samples to see how to use Lottie with Xamarin Android and iOS.

**Comment by halukmy** [comment]
@fabionuno  thanks bro!!!
