### ISSUE TITLE
Unable to link properly on iOS

### ISSUE THREAD

**Issue by SaigueFault** [martijn00/LottieXamarin#65]
I'm using Xamarin Forms and integrated Lottie. It works wonderfully on the simulator / my devices, however, I can't generate an IPA:

2>  error: Invalid bitcode signature
2>  clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(747,3): error : Native linking error: error: Invalid bitcode signature
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(747,3): error : Native linking failed. Please review the build log.

Removing your package solved the issue.

**Comment by martijn00** [comment]
Try to use the correct architecture and download the latest updates.
