### ISSUE TITLE
Samples not running

### ISSUE THREAD

**Issue by adamhill** [martijn00/LottieXamarin#7]
Should it be working yet? It is not, in either OS for me.

**Comment by matthewrdev** [comment]
@adamhill Could you include your code so I can have a look?

We'll need a small sample of what you've tried in order to help out; Martin and I will setup docs for integrating the AnimationView in the next few days.

**Comment by ryanherman** [comment]
I got them working on both platforms but had to use the Renderers.  But...the iOS comes displays but does not animate and the Android animates.

**Comment by adamhill** [comment]
I was just trying to run the samples in the emulators and saw nothing as I picked examples and executed the animations. This happened on iOS and Android (iOS 9.3 and Android 5.1)

**Comment by martijn00** [comment]
Do you have anymore details about this?

**Comment by Vaibhav-Khanna** [comment]
Nothing happens after view is loaded

**Comment by ryanherman** [comment]
I had to compile the Example.Forms first then run it and I see the animation.  I only tested this on iOS because my iOS project isn't working :(.

**Comment by starkovss** [comment]
Hi, I'm also having some issues when trying to run examples.

1)  Unzip 
2) Open sln using VS 2015
3) Rebuild Solution 

`
Getting these errors

**Error**	Build action '**EmbeddedResource**' is not supported by one or more of the project's targets.		Example.Forms (Examples\Example.Forms\Example.Forms)		...LottieXamarin-develop\LottieXamarin-develop\Examples\Example.Forms\Example.Forms\MainPage.xaml

**Error**	CS0426	The type name '**ICancellable**' does not exist in the type 'LottieComposition'		Lottie.Droid	...\LottieXamarin-develop\LottieXamarin-develop\Lottie.Droid\Additions\LottieComposition.cs		15	Active

**Error**	CS0426	The type name '**IOnCompositionLoadedListener**' does not exist in the type 'LottieComposition'		Lottie.Droid	...\LottieXamarin-develop\LottieXamarin-develop\Lottie.Droid\Additions\LottieComposition.cs		141	Active

**Error**	CS0103	The name '**InitializeComponent**' does not exist in the current context		Example.Forms	...\LottieXamarin-develop\LottieXamarin-develop\Examples\Example.Forms\Example.Forms\App.xaml.cs		14	Active

**Error**	CS0103	The name '**InitializeComponent**' does not exist in the current context		Example.Forms	...\LottieXamarin-develop\LottieXamarin-develop\Examples\Example.Forms\Example.Forms\MainPage.xaml.cs		10	Active

**Error**	CS0120	An object reference is required for the non-static field, method, or property '**AnimationView.Progress**'		Example.Forms	...\LottieXamarin-develop\LottieXamarin-develop\Examples\Example.Forms\Example.Forms\MainPage.xaml.cs		15	Active
			
**Error**	Build action '**EmbeddedResource**' is not supported by one or more of the project's targets.		Example.Forms (Examples\Example.Forms\Example.Forms)		...\LottieXamarin-develop\LottieXamarin-develop\Examples\Example.Forms\Example.Forms\App.xaml

Error	The "ResolveLibraryProjectImports" task failed unexpectedly.

`

**Comment by rafasaints** [comment]
Hi guys, the animation not running issue is ok now?? the demo i pick to xamarin forms dont run.
