### ISSUE TITLE
Tap and play on Xamarin forms

### ISSUE THREAD

**Issue by georgemichailou** [martijn00/LottieXamarin#70]
I add Gesture Recognizer on AnimationView and i call Play() here but nothing happened. Any help ?

			var tapGestureRecognizer = new TapGestureRecognizer() { NumberOfTapsRequired = 1 };
			tapGestureRecognizer.Tapped += (s, e) =>
			{
				AnimationView.Play();
			};
			AnimationView.GestureRecognizers.Add(tapGestureRecognizer);

**Comment by danilkurkin1** [comment]
Need to Start animation on UI thread...
