### ISSUE TITLE
Only Partial Animation is Showing

### ISSUE THREAD

**Issue by adamfisher** [martijn00/LottieXamarin#72]
I attempted to load the example [Pink Drink Machine](https://www.lottiefiles.com/351-pink-drink-machine) from the Lottie Files website. The animation works! It looks super cool. The only problem is it only renders part of the image. If you compare the bolts and the plunger in the canister, they do not even show up. It's like pieces of the animation are missing.

This is my Xamarin Forms code:

```
public partial class AnimationDemoAppPage : ContentPage
    {
        public AnimationDemoAppPage()
        {
            InitializeComponent();

            var animationView = new AnimationView()
            {
                Animation = "pink_drink_machine.json",
                Loop = true,
                AutoPlay = true,
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.Yellow
            };

            Content = animationView;
        }
    }
```
And this is the resulting image on the iOS simulator. I also tried it on a real device. I also tried a different lottie file altogether and get the same result. I only added the yellow background to see if it made a difference in the bolts showing up. Any ideas on why the animation is only partially showing up?

<img width="500" src="https://user-images.githubusercontent.com/1834711/27608330-19b6b48c-5b55-11e7-895d-db4e56f018c6.png" />

**Comment by adamfisher** [comment]
Anyone have any idea why only part of the animation would render? I am able to use the Lottie Previewer app and when I scan it loads correctly and in its entirety.

**Comment by martijn00** [comment]
Try the latest version.
