### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by AnaghSharma** [martijn00/LottieXamarin#74]
README does not say anything about the support for macOS and TvOS.

1. If the library supports macOS and TvOS, then what is the minimum version that is supported?
2. There are no examples on the usage of the library in macOS/TvOS apps.

I believe README should be updated accordingly.

**Comment by fabionuno** [comment]
Hi @AnaghSharma 

1.  The minimum versions supported by this library are macOS 10.10, tvOS 9.0 and iOS 8.0

2. You can find some simple examples for macOS version and tvOS in the folder [Examples](https://github.com/martijn00/LottieXamarin/tree/develop/Examples)
For a more complete example you can check the iOS version.
