### ISSUE TITLE
Xamarin.Forms lottie animation with fonts not working

### ISSUE THREAD

**Issue by lucabee** [martijn00/LottieXamarin#77]
I have download the HelloWorld json sample from 
[lottie-android/LottieSample/src/main/assets/Hello World.json](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/assets/Hello%20World.json)

This example does not work on Xamarin.Forms.

Other animations samples without fonts works properly.

**Comment by martijn00** [comment]
Look at the samples in this repo. They are working.

**Comment by lucabee** [comment]
I made some tests with Example.Forms.iOS project from this repo.
The animation work properly using LottieLogo1.json, but if I replace it with this animation 

[lottie-android/LottieSample/src/main/assets/Hello World.json](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/assets/Hello%20World.json)
the animation seems not to work.
Maybe it need some additional code to load fonts?
I can't find any documentation about.
Thanks for help
