### ISSUE TITLE
After Effects Animation with wiggle not working

### ISSUE THREAD

**Issue by dcama** [martijn00/LottieXamarin#81]
I have made this animation with wiggle on position, it works on html5 but not in lottie.forms
[AnimationAfter.zip](https://github.com/martijn00/LottieXamarin/files/1188055/AnimationAfter.zip)

**Comment by fabionuno** [comment]
Unfortunately expressions aren't supported by Lottie yet
http://airbnb.io/lottie/supported-features.html
