### ISSUE TITLE
You must set an images folder Exception

### ISSUE THREAD

**Issue by createS0ftware** [martijn00/LottieXamarin#95]
` java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder

08-21 12:45:44.562 E/AndroidRuntime( 9788): at com.airbnb.lottie.ImageAssetManager.bitmapForId(ImageAssetManager.java:73)

08-21 12:45:44.562 E/AndroidRuntime( 9788): at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:537)
...`

Hi - i keep getting the above error and i can't seem to find how to set the images folder. Is there a way programatically or in the JSON ?

Below is  a portion of my JSON. Trying to run a forms page on an Android device API24

`{
  "v": "4.10.1",
  "fr": 15,
  "ip": 0,
  "op": 59,
  "w": 768,
  "h": 458,
  "nm": "Splashscreen",
  "ddd": 0,
  "assets": [
    {
      "id": "image_0",
      "w": 1191,
      "h": 842,
      "u": "images/",
      "p": "img_0.png"
    },
....`

Thanks

**Comment by hedza06** [comment]
Does anyone have a solution for this issue?

**Comment by MatFillion** [comment]
ImageAssetFolder is a property on LottieAnimationView.

**Comment by encrypt0r** [comment]
@MatFillion how would you specify the image asset folder in xamarin forms? Exposing the same property would be very helpful

**Comment by MatFillion** [comment]
Yeah seems missing from the x.f control. You could add a effect in your project on the lottie control. Or make a PR on this repo to add it? I don't know if there was a reason it's not exposed.

**Comment by encrypt0r** [comment]
@MatFillion I tried to do that, but there are just too many build errors for me to be able to work on it, maybe @martijn00 can take a look at it?

**Comment by martijn00** [comment]
You need to run this on Visual Studio 15.7 to be able to compile it. VS4Mac doesn't work at the moment. If you make a PR with work in progress which should work but doesn't compile for you, i can always have a look at my machine, so i would love to see the PR coming!

**Comment by encrypt0r** [comment]
@martijn00 I'd love to do that, let's see what we can do...

**Comment by encrypt0r** [comment]
@martijn00 That'd very good indeed, I will work on it as soon as I have the time because that's currently a roadblock for me.
